/*
Cobo Wallet as a Service 2.0

API version: 1.0.0
Contact: support@cobo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package waas2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeleteWalletById201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteWalletById201Response{}

// DeleteWalletById201Response struct for DeleteWalletById201Response
type DeleteWalletById201Response struct {
	// Whether the request to delete the wallet has been successfully submitted. - `true`: The request to delete the wallet has been successfully submitted. - `false`: The request to delete the wallet has not been submitted. 
	Submitted bool `json:"submitted"`
}

type _DeleteWalletById201Response DeleteWalletById201Response

// NewDeleteWalletById201Response instantiates a new DeleteWalletById201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteWalletById201Response(submitted bool) *DeleteWalletById201Response {
	this := DeleteWalletById201Response{}
	this.Submitted = submitted
	return &this
}

// NewDeleteWalletById201ResponseWithDefaults instantiates a new DeleteWalletById201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteWalletById201ResponseWithDefaults() *DeleteWalletById201Response {
	this := DeleteWalletById201Response{}
	return &this
}

// GetSubmitted returns the Submitted field value
func (o *DeleteWalletById201Response) GetSubmitted() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Submitted
}

// GetSubmittedOk returns a tuple with the Submitted field value
// and a boolean to check if the value has been set.
func (o *DeleteWalletById201Response) GetSubmittedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Submitted, true
}

// SetSubmitted sets field value
func (o *DeleteWalletById201Response) SetSubmitted(v bool) {
	o.Submitted = v
}

func (o DeleteWalletById201Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteWalletById201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["submitted"] = o.Submitted
	return toSerialize, nil
}

func (o *DeleteWalletById201Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"submitted",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteWalletById201Response := _DeleteWalletById201Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteWalletById201Response)

	if err != nil {
		return err
	}

	*o = DeleteWalletById201Response(varDeleteWalletById201Response)

	return err
}

type NullableDeleteWalletById201Response struct {
	value *DeleteWalletById201Response
	isSet bool
}

func (v NullableDeleteWalletById201Response) Get() *DeleteWalletById201Response {
	return v.value
}

func (v *NullableDeleteWalletById201Response) Set(val *DeleteWalletById201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteWalletById201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteWalletById201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteWalletById201Response(val *DeleteWalletById201Response) *NullableDeleteWalletById201Response {
	return &NullableDeleteWalletById201Response{value: val, isSet: true}
}

func (v NullableDeleteWalletById201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteWalletById201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


