/*
Cobo Wallet as a Service 2.0

API version: 1.0.0
Contact: support@cobo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package CoboWaas2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TransactionCustodialWalletDestination type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TransactionCustodialWalletDestination{}

// TransactionCustodialWalletDestination The information about the transaction destination.
type TransactionCustodialWalletDestination struct {
	DestinationType TransactionDestinationType `json:"destination_type"`
	// The wallet ID.
	WalletId string `json:"wallet_id"`
	// The token ID, which is the unique identifier of a token. You can retrieve the IDs of all the tokens you can use by calling [List organization enabled tokens](/v2/api-references/wallets/list-organization-enabled-tokens).
	TokenId string `json:"token_id"`
	// (This concept applies to Exchange Wallets only) The asset ID. An asset is a digital representation of a valuable resource on a blockchain network. Exchange Wallets group your holdings by asset, even if the same asset exists on different blockchains. For example, if your Exchange Wallet has 1 USDT on Ethereum and 1 USDT on TRON, then your asset balance is 2 USDT.
	AssetId *string `json:"asset_id,omitempty"`
	// The destination address.
	Address string `json:"address"`
	// The memo that identifies a transaction in order to credit the correct account. For transfers out of Cobo Portal, it is highly recommended to include a memo for the chains such as XRP, EOS, XLM, IOST, BNB_BNB, ATOM, LUNA, and TON.
	Memo *string `json:"memo,omitempty"`
	// The transaction amount. For exmaole, if you trade 1.5 ETH, then the amount is `1.5`. 
	Amount string `json:"amount"`
}

type _TransactionCustodialWalletDestination TransactionCustodialWalletDestination

// NewTransactionCustodialWalletDestination instantiates a new TransactionCustodialWalletDestination object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTransactionCustodialWalletDestination(destinationType TransactionDestinationType, walletId string, tokenId string, address string, amount string) *TransactionCustodialWalletDestination {
	this := TransactionCustodialWalletDestination{}
	this.DestinationType = destinationType
	this.WalletId = walletId
	this.TokenId = tokenId
	this.Address = address
	this.Amount = amount
	return &this
}

// NewTransactionCustodialWalletDestinationWithDefaults instantiates a new TransactionCustodialWalletDestination object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTransactionCustodialWalletDestinationWithDefaults() *TransactionCustodialWalletDestination {
	this := TransactionCustodialWalletDestination{}
	return &this
}

// GetDestinationType returns the DestinationType field value
func (o *TransactionCustodialWalletDestination) GetDestinationType() TransactionDestinationType {
	if o == nil {
		var ret TransactionDestinationType
		return ret
	}

	return o.DestinationType
}

// GetDestinationTypeOk returns a tuple with the DestinationType field value
// and a boolean to check if the value has been set.
func (o *TransactionCustodialWalletDestination) GetDestinationTypeOk() (*TransactionDestinationType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DestinationType, true
}

// SetDestinationType sets field value
func (o *TransactionCustodialWalletDestination) SetDestinationType(v TransactionDestinationType) {
	o.DestinationType = v
}

// GetWalletId returns the WalletId field value
func (o *TransactionCustodialWalletDestination) GetWalletId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WalletId
}

// GetWalletIdOk returns a tuple with the WalletId field value
// and a boolean to check if the value has been set.
func (o *TransactionCustodialWalletDestination) GetWalletIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WalletId, true
}

// SetWalletId sets field value
func (o *TransactionCustodialWalletDestination) SetWalletId(v string) {
	o.WalletId = v
}

// GetTokenId returns the TokenId field value
func (o *TransactionCustodialWalletDestination) GetTokenId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenId
}

// GetTokenIdOk returns a tuple with the TokenId field value
// and a boolean to check if the value has been set.
func (o *TransactionCustodialWalletDestination) GetTokenIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenId, true
}

// SetTokenId sets field value
func (o *TransactionCustodialWalletDestination) SetTokenId(v string) {
	o.TokenId = v
}

// GetAssetId returns the AssetId field value if set, zero value otherwise.
func (o *TransactionCustodialWalletDestination) GetAssetId() string {
	if o == nil || IsNil(o.AssetId) {
		var ret string
		return ret
	}
	return *o.AssetId
}

// GetAssetIdOk returns a tuple with the AssetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionCustodialWalletDestination) GetAssetIdOk() (*string, bool) {
	if o == nil || IsNil(o.AssetId) {
		return nil, false
	}
	return o.AssetId, true
}

// HasAssetId returns a boolean if a field has been set.
func (o *TransactionCustodialWalletDestination) HasAssetId() bool {
	if o != nil && !IsNil(o.AssetId) {
		return true
	}

	return false
}

// SetAssetId gets a reference to the given string and assigns it to the AssetId field.
func (o *TransactionCustodialWalletDestination) SetAssetId(v string) {
	o.AssetId = &v
}

// GetAddress returns the Address field value
func (o *TransactionCustodialWalletDestination) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *TransactionCustodialWalletDestination) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *TransactionCustodialWalletDestination) SetAddress(v string) {
	o.Address = v
}

// GetMemo returns the Memo field value if set, zero value otherwise.
func (o *TransactionCustodialWalletDestination) GetMemo() string {
	if o == nil || IsNil(o.Memo) {
		var ret string
		return ret
	}
	return *o.Memo
}

// GetMemoOk returns a tuple with the Memo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TransactionCustodialWalletDestination) GetMemoOk() (*string, bool) {
	if o == nil || IsNil(o.Memo) {
		return nil, false
	}
	return o.Memo, true
}

// HasMemo returns a boolean if a field has been set.
func (o *TransactionCustodialWalletDestination) HasMemo() bool {
	if o != nil && !IsNil(o.Memo) {
		return true
	}

	return false
}

// SetMemo gets a reference to the given string and assigns it to the Memo field.
func (o *TransactionCustodialWalletDestination) SetMemo(v string) {
	o.Memo = &v
}

// GetAmount returns the Amount field value
func (o *TransactionCustodialWalletDestination) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *TransactionCustodialWalletDestination) GetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *TransactionCustodialWalletDestination) SetAmount(v string) {
	o.Amount = v
}

func (o TransactionCustodialWalletDestination) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TransactionCustodialWalletDestination) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["destination_type"] = o.DestinationType
	toSerialize["wallet_id"] = o.WalletId
	toSerialize["token_id"] = o.TokenId
	if !IsNil(o.AssetId) {
		toSerialize["asset_id"] = o.AssetId
	}
	toSerialize["address"] = o.Address
	if !IsNil(o.Memo) {
		toSerialize["memo"] = o.Memo
	}
	toSerialize["amount"] = o.Amount
	return toSerialize, nil
}

func (o *TransactionCustodialWalletDestination) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"destination_type",
		"wallet_id",
		"token_id",
		"address",
		"amount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTransactionCustodialWalletDestination := _TransactionCustodialWalletDestination{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTransactionCustodialWalletDestination)

	if err != nil {
		return err
	}

	*o = TransactionCustodialWalletDestination(varTransactionCustodialWalletDestination)

	return err
}

type NullableTransactionCustodialWalletDestination struct {
	value *TransactionCustodialWalletDestination
	isSet bool
}

func (v NullableTransactionCustodialWalletDestination) Get() *TransactionCustodialWalletDestination {
	return v.value
}

func (v *NullableTransactionCustodialWalletDestination) Set(val *TransactionCustodialWalletDestination) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionCustodialWalletDestination) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionCustodialWalletDestination) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionCustodialWalletDestination(val *TransactionCustodialWalletDestination) *NullableTransactionCustodialWalletDestination {
	return &NullableTransactionCustodialWalletDestination{value: val, isSet: true}
}

func (v NullableTransactionCustodialWalletDestination) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionCustodialWalletDestination) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


