/*
Cobo Wallet as a Service 2.0

Contact: help@cobo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cobo_waas2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdatePaymentOrderRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdatePaymentOrderRequest{}

// UpdatePaymentOrderRequest struct for UpdatePaymentOrderRequest
type UpdatePaymentOrderRequest struct {
	// Whether to manually expire the order. If set to `true`, the order status will be updated to `Expired`.
	Expired bool `json:"expired"`
}

type _UpdatePaymentOrderRequest UpdatePaymentOrderRequest

// NewUpdatePaymentOrderRequest instantiates a new UpdatePaymentOrderRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdatePaymentOrderRequest(expired bool) *UpdatePaymentOrderRequest {
	this := UpdatePaymentOrderRequest{}
	this.Expired = expired
	return &this
}

// NewUpdatePaymentOrderRequestWithDefaults instantiates a new UpdatePaymentOrderRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatePaymentOrderRequestWithDefaults() *UpdatePaymentOrderRequest {
	this := UpdatePaymentOrderRequest{}
	return &this
}

// GetExpired returns the Expired field value
func (o *UpdatePaymentOrderRequest) GetExpired() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Expired
}

// GetExpiredOk returns a tuple with the Expired field value
// and a boolean to check if the value has been set.
func (o *UpdatePaymentOrderRequest) GetExpiredOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Expired, true
}

// SetExpired sets field value
func (o *UpdatePaymentOrderRequest) SetExpired(v bool) {
	o.Expired = v
}

func (o UpdatePaymentOrderRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdatePaymentOrderRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["expired"] = o.Expired
	return toSerialize, nil
}

func (o *UpdatePaymentOrderRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"expired",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdatePaymentOrderRequest := _UpdatePaymentOrderRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdatePaymentOrderRequest)

	if err != nil {
		return err
	}

	*o = UpdatePaymentOrderRequest(varUpdatePaymentOrderRequest)

	return err
}

type NullableUpdatePaymentOrderRequest struct {
	value *UpdatePaymentOrderRequest
	isSet bool
}

func (v NullableUpdatePaymentOrderRequest) Get() *UpdatePaymentOrderRequest {
	return v.value
}

func (v *NullableUpdatePaymentOrderRequest) Set(val *UpdatePaymentOrderRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatePaymentOrderRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatePaymentOrderRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdatePaymentOrderRequest(val *UpdatePaymentOrderRequest) *NullableUpdatePaymentOrderRequest {
	return &NullableUpdatePaymentOrderRequest{value: val, isSet: true}
}

func (v NullableUpdatePaymentOrderRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatePaymentOrderRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


