/*
Cobo Wallet as a Service 2.0

Contact: help@cobo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cobo_waas2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TokenizationUpdateBlocklistAddressesParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenizationUpdateBlocklistAddressesParams{}

// TokenizationUpdateBlocklistAddressesParams struct for TokenizationUpdateBlocklistAddressesParams
type TokenizationUpdateBlocklistAddressesParams struct {
	Action TokenizationUpdateAddressAction `json:"action"`
	Source TokenizationTokenOperationSource `json:"source"`
	// A list of addresses to manage. For 'add' operations, notes can be provided. For 'remove' operations, notes are ignored.
	Addresses []TokenizationUpdateBlocklistAddressesParamsAddressesInner `json:"addresses"`
}

type _TokenizationUpdateBlocklistAddressesParams TokenizationUpdateBlocklistAddressesParams

// NewTokenizationUpdateBlocklistAddressesParams instantiates a new TokenizationUpdateBlocklistAddressesParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenizationUpdateBlocklistAddressesParams(action TokenizationUpdateAddressAction, source TokenizationTokenOperationSource, addresses []TokenizationUpdateBlocklistAddressesParamsAddressesInner) *TokenizationUpdateBlocklistAddressesParams {
	this := TokenizationUpdateBlocklistAddressesParams{}
	this.Action = action
	this.Source = source
	this.Addresses = addresses
	return &this
}

// NewTokenizationUpdateBlocklistAddressesParamsWithDefaults instantiates a new TokenizationUpdateBlocklistAddressesParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenizationUpdateBlocklistAddressesParamsWithDefaults() *TokenizationUpdateBlocklistAddressesParams {
	this := TokenizationUpdateBlocklistAddressesParams{}
	return &this
}

// GetAction returns the Action field value
func (o *TokenizationUpdateBlocklistAddressesParams) GetAction() TokenizationUpdateAddressAction {
	if o == nil {
		var ret TokenizationUpdateAddressAction
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *TokenizationUpdateBlocklistAddressesParams) GetActionOk() (*TokenizationUpdateAddressAction, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *TokenizationUpdateBlocklistAddressesParams) SetAction(v TokenizationUpdateAddressAction) {
	o.Action = v
}

// GetSource returns the Source field value
func (o *TokenizationUpdateBlocklistAddressesParams) GetSource() TokenizationTokenOperationSource {
	if o == nil {
		var ret TokenizationTokenOperationSource
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *TokenizationUpdateBlocklistAddressesParams) GetSourceOk() (*TokenizationTokenOperationSource, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *TokenizationUpdateBlocklistAddressesParams) SetSource(v TokenizationTokenOperationSource) {
	o.Source = v
}

// GetAddresses returns the Addresses field value
func (o *TokenizationUpdateBlocklistAddressesParams) GetAddresses() []TokenizationUpdateBlocklistAddressesParamsAddressesInner {
	if o == nil {
		var ret []TokenizationUpdateBlocklistAddressesParamsAddressesInner
		return ret
	}

	return o.Addresses
}

// GetAddressesOk returns a tuple with the Addresses field value
// and a boolean to check if the value has been set.
func (o *TokenizationUpdateBlocklistAddressesParams) GetAddressesOk() ([]TokenizationUpdateBlocklistAddressesParamsAddressesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Addresses, true
}

// SetAddresses sets field value
func (o *TokenizationUpdateBlocklistAddressesParams) SetAddresses(v []TokenizationUpdateBlocklistAddressesParamsAddressesInner) {
	o.Addresses = v
}

func (o TokenizationUpdateBlocklistAddressesParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenizationUpdateBlocklistAddressesParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	toSerialize["source"] = o.Source
	toSerialize["addresses"] = o.Addresses
	return toSerialize, nil
}

func (o *TokenizationUpdateBlocklistAddressesParams) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action",
		"source",
		"addresses",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTokenizationUpdateBlocklistAddressesParams := _TokenizationUpdateBlocklistAddressesParams{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTokenizationUpdateBlocklistAddressesParams)

	if err != nil {
		return err
	}

	*o = TokenizationUpdateBlocklistAddressesParams(varTokenizationUpdateBlocklistAddressesParams)

	return err
}

type NullableTokenizationUpdateBlocklistAddressesParams struct {
	value *TokenizationUpdateBlocklistAddressesParams
	isSet bool
}

func (v NullableTokenizationUpdateBlocklistAddressesParams) Get() *TokenizationUpdateBlocklistAddressesParams {
	return v.value
}

func (v *NullableTokenizationUpdateBlocklistAddressesParams) Set(val *TokenizationUpdateBlocklistAddressesParams) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenizationUpdateBlocklistAddressesParams) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenizationUpdateBlocklistAddressesParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenizationUpdateBlocklistAddressesParams(val *TokenizationUpdateBlocklistAddressesParams) *NullableTokenizationUpdateBlocklistAddressesParams {
	return &NullableTokenizationUpdateBlocklistAddressesParams{value: val, isSet: true}
}

func (v NullableTokenizationUpdateBlocklistAddressesParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenizationUpdateBlocklistAddressesParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


