/*
Cobo Wallet as a Service 2.0

Contact: help@cobo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cobo_waas2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PoolSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PoolSummary{}

// PoolSummary The basic information of the staking pool.
type PoolSummary struct {
	// The ID of the staking pool. A staking pool is a pairing of a staking protocol and a specific type of token.
	Id string `json:"id"`
	// The chain ID.
	ChainId string `json:"chain_id"`
	// The name of the protocol.
	Protocol string `json:"protocol"`
	// The URL of the protocol's icon.
	ProtocolIconUrl string `json:"protocol_icon_url"`
	// The wallet type. Possible values include:  - `Custodial`: [Custodial Wallets](https://manuals.cobo.com/en/portal/custodial-wallets/introduction)  - `MPC`: [MPC Wallets](https://manuals.cobo.com/en/portal/mpc-wallets/introduction)  - `SmartContract`: [Smart Contract Wallets](https://manuals.cobo.com/en/portal/smart-contract-wallets/introduction)  - `Exchange`: [Exchange Wallets](https://manuals.cobo.com/en/portal/exchange-wallets/introduction) 
	SupportedWalletTypes []WalletType `json:"supported_wallet_types"`
	// The wallet subtype. Possible values include: - `Asset`: Custodial Wallets (Asset Wallets). - `Web3`: Custodial Wallets (Web3  Wallets). - `Org-Controlled`: MPC Wallets (Organization-Controlled Wallets). - `User-Controlled`: MPC Wallets (User-Controlled Wallets). - `Safe{Wallet}`: Smart Contract Wallets (Safe{Wallet}). - `Main`: Exchange Wallets (Main Account). - `Sub`: Exchange Wallets (Sub Account). 
	SupportedWalletSubtypes []WalletSubtype `json:"supported_wallet_subtypes"`
	// The token ID.
	TokenId string `json:"token_id"`
	// The estimated annual percentage rate (APR).
	EstApr float32 `json:"est_apr"`
}

type _PoolSummary PoolSummary

// NewPoolSummary instantiates a new PoolSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPoolSummary(id string, chainId string, protocol string, protocolIconUrl string, supportedWalletTypes []WalletType, supportedWalletSubtypes []WalletSubtype, tokenId string, estApr float32) *PoolSummary {
	this := PoolSummary{}
	this.Id = id
	this.ChainId = chainId
	this.Protocol = protocol
	this.ProtocolIconUrl = protocolIconUrl
	this.SupportedWalletTypes = supportedWalletTypes
	this.SupportedWalletSubtypes = supportedWalletSubtypes
	this.TokenId = tokenId
	this.EstApr = estApr
	return &this
}

// NewPoolSummaryWithDefaults instantiates a new PoolSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPoolSummaryWithDefaults() *PoolSummary {
	this := PoolSummary{}
	return &this
}

// GetId returns the Id field value
func (o *PoolSummary) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PoolSummary) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PoolSummary) SetId(v string) {
	o.Id = v
}

// GetChainId returns the ChainId field value
func (o *PoolSummary) GetChainId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChainId
}

// GetChainIdOk returns a tuple with the ChainId field value
// and a boolean to check if the value has been set.
func (o *PoolSummary) GetChainIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChainId, true
}

// SetChainId sets field value
func (o *PoolSummary) SetChainId(v string) {
	o.ChainId = v
}

// GetProtocol returns the Protocol field value
func (o *PoolSummary) GetProtocol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Protocol
}

// GetProtocolOk returns a tuple with the Protocol field value
// and a boolean to check if the value has been set.
func (o *PoolSummary) GetProtocolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Protocol, true
}

// SetProtocol sets field value
func (o *PoolSummary) SetProtocol(v string) {
	o.Protocol = v
}

// GetProtocolIconUrl returns the ProtocolIconUrl field value
func (o *PoolSummary) GetProtocolIconUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProtocolIconUrl
}

// GetProtocolIconUrlOk returns a tuple with the ProtocolIconUrl field value
// and a boolean to check if the value has been set.
func (o *PoolSummary) GetProtocolIconUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProtocolIconUrl, true
}

// SetProtocolIconUrl sets field value
func (o *PoolSummary) SetProtocolIconUrl(v string) {
	o.ProtocolIconUrl = v
}

// GetSupportedWalletTypes returns the SupportedWalletTypes field value
func (o *PoolSummary) GetSupportedWalletTypes() []WalletType {
	if o == nil {
		var ret []WalletType
		return ret
	}

	return o.SupportedWalletTypes
}

// GetSupportedWalletTypesOk returns a tuple with the SupportedWalletTypes field value
// and a boolean to check if the value has been set.
func (o *PoolSummary) GetSupportedWalletTypesOk() ([]WalletType, bool) {
	if o == nil {
		return nil, false
	}
	return o.SupportedWalletTypes, true
}

// SetSupportedWalletTypes sets field value
func (o *PoolSummary) SetSupportedWalletTypes(v []WalletType) {
	o.SupportedWalletTypes = v
}

// GetSupportedWalletSubtypes returns the SupportedWalletSubtypes field value
func (o *PoolSummary) GetSupportedWalletSubtypes() []WalletSubtype {
	if o == nil {
		var ret []WalletSubtype
		return ret
	}

	return o.SupportedWalletSubtypes
}

// GetSupportedWalletSubtypesOk returns a tuple with the SupportedWalletSubtypes field value
// and a boolean to check if the value has been set.
func (o *PoolSummary) GetSupportedWalletSubtypesOk() ([]WalletSubtype, bool) {
	if o == nil {
		return nil, false
	}
	return o.SupportedWalletSubtypes, true
}

// SetSupportedWalletSubtypes sets field value
func (o *PoolSummary) SetSupportedWalletSubtypes(v []WalletSubtype) {
	o.SupportedWalletSubtypes = v
}

// GetTokenId returns the TokenId field value
func (o *PoolSummary) GetTokenId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenId
}

// GetTokenIdOk returns a tuple with the TokenId field value
// and a boolean to check if the value has been set.
func (o *PoolSummary) GetTokenIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenId, true
}

// SetTokenId sets field value
func (o *PoolSummary) SetTokenId(v string) {
	o.TokenId = v
}

// GetEstApr returns the EstApr field value
func (o *PoolSummary) GetEstApr() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.EstApr
}

// GetEstAprOk returns a tuple with the EstApr field value
// and a boolean to check if the value has been set.
func (o *PoolSummary) GetEstAprOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EstApr, true
}

// SetEstApr sets field value
func (o *PoolSummary) SetEstApr(v float32) {
	o.EstApr = v
}

func (o PoolSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PoolSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["chain_id"] = o.ChainId
	toSerialize["protocol"] = o.Protocol
	toSerialize["protocol_icon_url"] = o.ProtocolIconUrl
	toSerialize["supported_wallet_types"] = o.SupportedWalletTypes
	toSerialize["supported_wallet_subtypes"] = o.SupportedWalletSubtypes
	toSerialize["token_id"] = o.TokenId
	toSerialize["est_apr"] = o.EstApr
	return toSerialize, nil
}

func (o *PoolSummary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"chain_id",
		"protocol",
		"protocol_icon_url",
		"supported_wallet_types",
		"supported_wallet_subtypes",
		"token_id",
		"est_apr",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPoolSummary := _PoolSummary{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPoolSummary)

	if err != nil {
		return err
	}

	*o = PoolSummary(varPoolSummary)

	return err
}

type NullablePoolSummary struct {
	value *PoolSummary
	isSet bool
}

func (v NullablePoolSummary) Get() *PoolSummary {
	return v.value
}

func (v *NullablePoolSummary) Set(val *PoolSummary) {
	v.value = val
	v.isSet = true
}

func (v NullablePoolSummary) IsSet() bool {
	return v.isSet
}

func (v *NullablePoolSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePoolSummary(val *PoolSummary) *NullablePoolSummary {
	return &NullablePoolSummary{value: val, isSet: true}
}

func (v NullablePoolSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePoolSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


