/*
Cobo Wallet as a Service 2.0

Contact: help@cobo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cobo_waas2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MerchantKycAddress type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MerchantKycAddress{}

// MerchantKycAddress struct for MerchantKycAddress
type MerchantKycAddress struct {
	// The country.
	Country string `json:"country"`
	// The state or province.
	State string `json:"state"`
	// The city.
	City string `json:"city"`
	// The postal code.
	Postcode string `json:"postcode"`
	// The address line.
	Line1 string `json:"line1"`
}

type _MerchantKycAddress MerchantKycAddress

// NewMerchantKycAddress instantiates a new MerchantKycAddress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMerchantKycAddress(country string, state string, city string, postcode string, line1 string) *MerchantKycAddress {
	this := MerchantKycAddress{}
	this.Country = country
	this.State = state
	this.City = city
	this.Postcode = postcode
	this.Line1 = line1
	return &this
}

// NewMerchantKycAddressWithDefaults instantiates a new MerchantKycAddress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMerchantKycAddressWithDefaults() *MerchantKycAddress {
	this := MerchantKycAddress{}
	return &this
}

// GetCountry returns the Country field value
func (o *MerchantKycAddress) GetCountry() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Country
}

// GetCountryOk returns a tuple with the Country field value
// and a boolean to check if the value has been set.
func (o *MerchantKycAddress) GetCountryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Country, true
}

// SetCountry sets field value
func (o *MerchantKycAddress) SetCountry(v string) {
	o.Country = v
}

// GetState returns the State field value
func (o *MerchantKycAddress) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *MerchantKycAddress) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *MerchantKycAddress) SetState(v string) {
	o.State = v
}

// GetCity returns the City field value
func (o *MerchantKycAddress) GetCity() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.City
}

// GetCityOk returns a tuple with the City field value
// and a boolean to check if the value has been set.
func (o *MerchantKycAddress) GetCityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.City, true
}

// SetCity sets field value
func (o *MerchantKycAddress) SetCity(v string) {
	o.City = v
}

// GetPostcode returns the Postcode field value
func (o *MerchantKycAddress) GetPostcode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Postcode
}

// GetPostcodeOk returns a tuple with the Postcode field value
// and a boolean to check if the value has been set.
func (o *MerchantKycAddress) GetPostcodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Postcode, true
}

// SetPostcode sets field value
func (o *MerchantKycAddress) SetPostcode(v string) {
	o.Postcode = v
}

// GetLine1 returns the Line1 field value
func (o *MerchantKycAddress) GetLine1() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Line1
}

// GetLine1Ok returns a tuple with the Line1 field value
// and a boolean to check if the value has been set.
func (o *MerchantKycAddress) GetLine1Ok() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Line1, true
}

// SetLine1 sets field value
func (o *MerchantKycAddress) SetLine1(v string) {
	o.Line1 = v
}

func (o MerchantKycAddress) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MerchantKycAddress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["country"] = o.Country
	toSerialize["state"] = o.State
	toSerialize["city"] = o.City
	toSerialize["postcode"] = o.Postcode
	toSerialize["line1"] = o.Line1
	return toSerialize, nil
}

func (o *MerchantKycAddress) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"country",
		"state",
		"city",
		"postcode",
		"line1",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMerchantKycAddress := _MerchantKycAddress{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMerchantKycAddress)

	if err != nil {
		return err
	}

	*o = MerchantKycAddress(varMerchantKycAddress)

	return err
}

type NullableMerchantKycAddress struct {
	value *MerchantKycAddress
	isSet bool
}

func (v NullableMerchantKycAddress) Get() *MerchantKycAddress {
	return v.value
}

func (v *NullableMerchantKycAddress) Set(val *MerchantKycAddress) {
	v.value = val
	v.isSet = true
}

func (v NullableMerchantKycAddress) IsSet() bool {
	return v.isSet
}

func (v *NullableMerchantKycAddress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMerchantKycAddress(val *MerchantKycAddress) *NullableMerchantKycAddress {
	return &NullableMerchantKycAddress{value: val, isSet: true}
}

func (v NullableMerchantKycAddress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMerchantKycAddress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


