/*
Cobo Wallet as a Service 2.0

Contact: help@cobo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cobo_waas2

import (
	"encoding/json"
)

// checks if the StrategyParams type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StrategyParams{}

// StrategyParams Strategy parameters for commission calculation
type StrategyParams struct {
	// Basis points
	Bps *string `json:"bps,omitempty"`
	// Minimum fee
	MinFee *string `json:"min_fee,omitempty"`
	// Additional fixed fee
	AdditionalFixedFee *string `json:"additional_fixed_fee,omitempty"`
}

// NewStrategyParams instantiates a new StrategyParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStrategyParams() *StrategyParams {
	this := StrategyParams{}
	return &this
}

// NewStrategyParamsWithDefaults instantiates a new StrategyParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStrategyParamsWithDefaults() *StrategyParams {
	this := StrategyParams{}
	return &this
}

// GetBps returns the Bps field value if set, zero value otherwise.
func (o *StrategyParams) GetBps() string {
	if o == nil || IsNil(o.Bps) {
		var ret string
		return ret
	}
	return *o.Bps
}

// GetBpsOk returns a tuple with the Bps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StrategyParams) GetBpsOk() (*string, bool) {
	if o == nil || IsNil(o.Bps) {
		return nil, false
	}
	return o.Bps, true
}

// HasBps returns a boolean if a field has been set.
func (o *StrategyParams) HasBps() bool {
	if o != nil && !IsNil(o.Bps) {
		return true
	}

	return false
}

// SetBps gets a reference to the given string and assigns it to the Bps field.
func (o *StrategyParams) SetBps(v string) {
	o.Bps = &v
}

// GetMinFee returns the MinFee field value if set, zero value otherwise.
func (o *StrategyParams) GetMinFee() string {
	if o == nil || IsNil(o.MinFee) {
		var ret string
		return ret
	}
	return *o.MinFee
}

// GetMinFeeOk returns a tuple with the MinFee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StrategyParams) GetMinFeeOk() (*string, bool) {
	if o == nil || IsNil(o.MinFee) {
		return nil, false
	}
	return o.MinFee, true
}

// HasMinFee returns a boolean if a field has been set.
func (o *StrategyParams) HasMinFee() bool {
	if o != nil && !IsNil(o.MinFee) {
		return true
	}

	return false
}

// SetMinFee gets a reference to the given string and assigns it to the MinFee field.
func (o *StrategyParams) SetMinFee(v string) {
	o.MinFee = &v
}

// GetAdditionalFixedFee returns the AdditionalFixedFee field value if set, zero value otherwise.
func (o *StrategyParams) GetAdditionalFixedFee() string {
	if o == nil || IsNil(o.AdditionalFixedFee) {
		var ret string
		return ret
	}
	return *o.AdditionalFixedFee
}

// GetAdditionalFixedFeeOk returns a tuple with the AdditionalFixedFee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StrategyParams) GetAdditionalFixedFeeOk() (*string, bool) {
	if o == nil || IsNil(o.AdditionalFixedFee) {
		return nil, false
	}
	return o.AdditionalFixedFee, true
}

// HasAdditionalFixedFee returns a boolean if a field has been set.
func (o *StrategyParams) HasAdditionalFixedFee() bool {
	if o != nil && !IsNil(o.AdditionalFixedFee) {
		return true
	}

	return false
}

// SetAdditionalFixedFee gets a reference to the given string and assigns it to the AdditionalFixedFee field.
func (o *StrategyParams) SetAdditionalFixedFee(v string) {
	o.AdditionalFixedFee = &v
}

func (o StrategyParams) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StrategyParams) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Bps) {
		toSerialize["bps"] = o.Bps
	}
	if !IsNil(o.MinFee) {
		toSerialize["min_fee"] = o.MinFee
	}
	if !IsNil(o.AdditionalFixedFee) {
		toSerialize["additional_fixed_fee"] = o.AdditionalFixedFee
	}
	return toSerialize, nil
}

type NullableStrategyParams struct {
	value *StrategyParams
	isSet bool
}

func (v NullableStrategyParams) Get() *StrategyParams {
	return v.value
}

func (v *NullableStrategyParams) Set(val *StrategyParams) {
	v.value = val
	v.isSet = true
}

func (v NullableStrategyParams) IsSet() bool {
	return v.isSet
}

func (v *NullableStrategyParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStrategyParams(val *StrategyParams) *NullableStrategyParams {
	return &NullableStrategyParams{value: val, isSet: true}
}

func (v NullableStrategyParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStrategyParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


