/*
Cobo Wallet as a Service 2.0

Contact: help@cobo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cobo_waas2

import (
	"encoding/json"
	"fmt"
)

// BankAccountStatus BankAccountStatus defines the status of the bank account: - `Pending`: The bank account is pending verification by Cobo. - `Approved`: The bank account has been approved by Cobo. - `Rejected`: The bank account has been rejected by Cobo. 
type BankAccountStatus string

// List of BankAccountStatus
const (
	BANKACCOUNTSTATUS_PENDING BankAccountStatus = "Pending"
	BANKACCOUNTSTATUS_APPROVED BankAccountStatus = "Approved"
	BANKACCOUNTSTATUS_REJECTED BankAccountStatus = "Rejected"
)

// All allowed values of BankAccountStatus enum
var AllowedBankAccountStatusEnumValues = []BankAccountStatus{
	"Pending",
	"Approved",
	"Rejected",
}

func (v *BankAccountStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := BankAccountStatus(value)
	for _, existing := range AllowedBankAccountStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}
	*v = BankAccountStatus("unknown")
	return nil
}

// NewBankAccountStatusFromValue returns a pointer to a valid BankAccountStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewBankAccountStatusFromValue(v string) (*BankAccountStatus, error) {
	ev := BankAccountStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for BankAccountStatus: valid values are %v", v, AllowedBankAccountStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v BankAccountStatus) IsValid() bool {
	for _, existing := range AllowedBankAccountStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to BankAccountStatus value
func (v BankAccountStatus) Ptr() *BankAccountStatus {
	return &v
}

type NullableBankAccountStatus struct {
	value *BankAccountStatus
	isSet bool
}

func (v NullableBankAccountStatus) Get() *BankAccountStatus {
	return v.value
}

func (v *NullableBankAccountStatus) Set(val *BankAccountStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableBankAccountStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableBankAccountStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBankAccountStatus(val *BankAccountStatus) *NullableBankAccountStatus {
	return &NullableBankAccountStatus{value: val, isSet: true}
}

func (v NullableBankAccountStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBankAccountStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

