/*
Cobo Wallet as a Service 2.0

Contact: help@cobo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cobo_waas2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TriggerTestPaymentsWebhookEventRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TriggerTestPaymentsWebhookEventRequest{}

// TriggerTestPaymentsWebhookEventRequest struct for TriggerTestPaymentsWebhookEventRequest
type TriggerTestPaymentsWebhookEventRequest struct {
	EventType WebhookEventType `json:"event_type"`
	// An optional object to customize the webhook event payload. Include only the fields you want to override.  The provided fields must match the webhook event data structure for the specified event type. For the full event data structure, refer to the `data.data` property in the response of [List all webhook events](https://www.cobo.com/developers/v2/api-references/developers--webhooks/list-all-webhook-events).  If this property is omitted, a default payload is returned. 
	OverrideData map[string]interface{} `json:"override_data,omitempty"`
}

type _TriggerTestPaymentsWebhookEventRequest TriggerTestPaymentsWebhookEventRequest

// NewTriggerTestPaymentsWebhookEventRequest instantiates a new TriggerTestPaymentsWebhookEventRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTriggerTestPaymentsWebhookEventRequest(eventType WebhookEventType) *TriggerTestPaymentsWebhookEventRequest {
	this := TriggerTestPaymentsWebhookEventRequest{}
	this.EventType = eventType
	return &this
}

// NewTriggerTestPaymentsWebhookEventRequestWithDefaults instantiates a new TriggerTestPaymentsWebhookEventRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTriggerTestPaymentsWebhookEventRequestWithDefaults() *TriggerTestPaymentsWebhookEventRequest {
	this := TriggerTestPaymentsWebhookEventRequest{}
	return &this
}

// GetEventType returns the EventType field value
func (o *TriggerTestPaymentsWebhookEventRequest) GetEventType() WebhookEventType {
	if o == nil {
		var ret WebhookEventType
		return ret
	}

	return o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value
// and a boolean to check if the value has been set.
func (o *TriggerTestPaymentsWebhookEventRequest) GetEventTypeOk() (*WebhookEventType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventType, true
}

// SetEventType sets field value
func (o *TriggerTestPaymentsWebhookEventRequest) SetEventType(v WebhookEventType) {
	o.EventType = v
}

// GetOverrideData returns the OverrideData field value if set, zero value otherwise.
func (o *TriggerTestPaymentsWebhookEventRequest) GetOverrideData() map[string]interface{} {
	if o == nil || IsNil(o.OverrideData) {
		var ret map[string]interface{}
		return ret
	}
	return o.OverrideData
}

// GetOverrideDataOk returns a tuple with the OverrideData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TriggerTestPaymentsWebhookEventRequest) GetOverrideDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.OverrideData) {
		return map[string]interface{}{}, false
	}
	return o.OverrideData, true
}

// HasOverrideData returns a boolean if a field has been set.
func (o *TriggerTestPaymentsWebhookEventRequest) HasOverrideData() bool {
	if o != nil && !IsNil(o.OverrideData) {
		return true
	}

	return false
}

// SetOverrideData gets a reference to the given map[string]interface{} and assigns it to the OverrideData field.
func (o *TriggerTestPaymentsWebhookEventRequest) SetOverrideData(v map[string]interface{}) {
	o.OverrideData = v
}

func (o TriggerTestPaymentsWebhookEventRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TriggerTestPaymentsWebhookEventRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["event_type"] = o.EventType
	if !IsNil(o.OverrideData) {
		toSerialize["override_data"] = o.OverrideData
	}
	return toSerialize, nil
}

func (o *TriggerTestPaymentsWebhookEventRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"event_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTriggerTestPaymentsWebhookEventRequest := _TriggerTestPaymentsWebhookEventRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTriggerTestPaymentsWebhookEventRequest)

	if err != nil {
		return err
	}

	*o = TriggerTestPaymentsWebhookEventRequest(varTriggerTestPaymentsWebhookEventRequest)

	return err
}

type NullableTriggerTestPaymentsWebhookEventRequest struct {
	value *TriggerTestPaymentsWebhookEventRequest
	isSet bool
}

func (v NullableTriggerTestPaymentsWebhookEventRequest) Get() *TriggerTestPaymentsWebhookEventRequest {
	return v.value
}

func (v *NullableTriggerTestPaymentsWebhookEventRequest) Set(val *TriggerTestPaymentsWebhookEventRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTriggerTestPaymentsWebhookEventRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTriggerTestPaymentsWebhookEventRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTriggerTestPaymentsWebhookEventRequest(val *TriggerTestPaymentsWebhookEventRequest) *NullableTriggerTestPaymentsWebhookEventRequest {
	return &NullableTriggerTestPaymentsWebhookEventRequest{value: val, isSet: true}
}

func (v NullableTriggerTestPaymentsWebhookEventRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTriggerTestPaymentsWebhookEventRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


