/*
Cobo Wallet as a Service 2.0

Contact: help@cobo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cobo_waas2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SafeWallet type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SafeWallet{}

// SafeWallet struct for SafeWallet
type SafeWallet struct {
	// The wallet ID.
	WalletId string `json:"wallet_id"`
	WalletType WalletType `json:"wallet_type"`
	WalletSubtype WalletSubtype `json:"wallet_subtype"`
	// The wallet name.
	Name string `json:"name"`
	// The ID of the owning organization.
	OrgId string `json:"org_id"`
	// Enable the auto sweep feature for the wallet
	EnableAutoSweep *bool `json:"enable_auto_sweep,omitempty"`
	// The ID of the chain on which the wallet operates.
	ChainId *string `json:"chain_id,omitempty"`
	SmartContractWalletType SmartContractWalletType `json:"smart_contract_wallet_type"`
	// The Smart Contract Wallet address.
	SafeAddress *string `json:"safe_address,omitempty"`
	// The signers of the Smart Contract Wallet.
	Signers []string `json:"signers,omitempty"`
	// The minimum number of confirmations required for the Smart Contract Wallet. 
	Threshold *int32 `json:"threshold,omitempty"`
	// The address of Cobo Safe.
	CoboSafeAddress *string `json:"cobo_safe_address,omitempty"`
	Initiator *SmartContractInitiator `json:"initiator,omitempty"`
}

type _SafeWallet SafeWallet

// NewSafeWallet instantiates a new SafeWallet object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSafeWallet(walletId string, walletType WalletType, walletSubtype WalletSubtype, name string, orgId string, smartContractWalletType SmartContractWalletType) *SafeWallet {
	this := SafeWallet{}
	this.WalletId = walletId
	this.WalletType = walletType
	this.WalletSubtype = walletSubtype
	this.Name = name
	this.OrgId = orgId
	this.SmartContractWalletType = smartContractWalletType
	return &this
}

// NewSafeWalletWithDefaults instantiates a new SafeWallet object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSafeWalletWithDefaults() *SafeWallet {
	this := SafeWallet{}
	var smartContractWalletType SmartContractWalletType = SMARTCONTRACTWALLETTYPE_SAFEWALLET
	this.SmartContractWalletType = smartContractWalletType
	return &this
}

// GetWalletId returns the WalletId field value
func (o *SafeWallet) GetWalletId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WalletId
}

// GetWalletIdOk returns a tuple with the WalletId field value
// and a boolean to check if the value has been set.
func (o *SafeWallet) GetWalletIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WalletId, true
}

// SetWalletId sets field value
func (o *SafeWallet) SetWalletId(v string) {
	o.WalletId = v
}

// GetWalletType returns the WalletType field value
func (o *SafeWallet) GetWalletType() WalletType {
	if o == nil {
		var ret WalletType
		return ret
	}

	return o.WalletType
}

// GetWalletTypeOk returns a tuple with the WalletType field value
// and a boolean to check if the value has been set.
func (o *SafeWallet) GetWalletTypeOk() (*WalletType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WalletType, true
}

// SetWalletType sets field value
func (o *SafeWallet) SetWalletType(v WalletType) {
	o.WalletType = v
}

// GetWalletSubtype returns the WalletSubtype field value
func (o *SafeWallet) GetWalletSubtype() WalletSubtype {
	if o == nil {
		var ret WalletSubtype
		return ret
	}

	return o.WalletSubtype
}

// GetWalletSubtypeOk returns a tuple with the WalletSubtype field value
// and a boolean to check if the value has been set.
func (o *SafeWallet) GetWalletSubtypeOk() (*WalletSubtype, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WalletSubtype, true
}

// SetWalletSubtype sets field value
func (o *SafeWallet) SetWalletSubtype(v WalletSubtype) {
	o.WalletSubtype = v
}

// GetName returns the Name field value
func (o *SafeWallet) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *SafeWallet) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *SafeWallet) SetName(v string) {
	o.Name = v
}

// GetOrgId returns the OrgId field value
func (o *SafeWallet) GetOrgId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrgId
}

// GetOrgIdOk returns a tuple with the OrgId field value
// and a boolean to check if the value has been set.
func (o *SafeWallet) GetOrgIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrgId, true
}

// SetOrgId sets field value
func (o *SafeWallet) SetOrgId(v string) {
	o.OrgId = v
}

// GetEnableAutoSweep returns the EnableAutoSweep field value if set, zero value otherwise.
func (o *SafeWallet) GetEnableAutoSweep() bool {
	if o == nil || IsNil(o.EnableAutoSweep) {
		var ret bool
		return ret
	}
	return *o.EnableAutoSweep
}

// GetEnableAutoSweepOk returns a tuple with the EnableAutoSweep field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SafeWallet) GetEnableAutoSweepOk() (*bool, bool) {
	if o == nil || IsNil(o.EnableAutoSweep) {
		return nil, false
	}
	return o.EnableAutoSweep, true
}

// HasEnableAutoSweep returns a boolean if a field has been set.
func (o *SafeWallet) HasEnableAutoSweep() bool {
	if o != nil && !IsNil(o.EnableAutoSweep) {
		return true
	}

	return false
}

// SetEnableAutoSweep gets a reference to the given bool and assigns it to the EnableAutoSweep field.
func (o *SafeWallet) SetEnableAutoSweep(v bool) {
	o.EnableAutoSweep = &v
}

// GetChainId returns the ChainId field value if set, zero value otherwise.
func (o *SafeWallet) GetChainId() string {
	if o == nil || IsNil(o.ChainId) {
		var ret string
		return ret
	}
	return *o.ChainId
}

// GetChainIdOk returns a tuple with the ChainId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SafeWallet) GetChainIdOk() (*string, bool) {
	if o == nil || IsNil(o.ChainId) {
		return nil, false
	}
	return o.ChainId, true
}

// HasChainId returns a boolean if a field has been set.
func (o *SafeWallet) HasChainId() bool {
	if o != nil && !IsNil(o.ChainId) {
		return true
	}

	return false
}

// SetChainId gets a reference to the given string and assigns it to the ChainId field.
func (o *SafeWallet) SetChainId(v string) {
	o.ChainId = &v
}

// GetSmartContractWalletType returns the SmartContractWalletType field value
func (o *SafeWallet) GetSmartContractWalletType() SmartContractWalletType {
	if o == nil {
		var ret SmartContractWalletType
		return ret
	}

	return o.SmartContractWalletType
}

// GetSmartContractWalletTypeOk returns a tuple with the SmartContractWalletType field value
// and a boolean to check if the value has been set.
func (o *SafeWallet) GetSmartContractWalletTypeOk() (*SmartContractWalletType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SmartContractWalletType, true
}

// SetSmartContractWalletType sets field value
func (o *SafeWallet) SetSmartContractWalletType(v SmartContractWalletType) {
	o.SmartContractWalletType = v
}

// GetSafeAddress returns the SafeAddress field value if set, zero value otherwise.
func (o *SafeWallet) GetSafeAddress() string {
	if o == nil || IsNil(o.SafeAddress) {
		var ret string
		return ret
	}
	return *o.SafeAddress
}

// GetSafeAddressOk returns a tuple with the SafeAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SafeWallet) GetSafeAddressOk() (*string, bool) {
	if o == nil || IsNil(o.SafeAddress) {
		return nil, false
	}
	return o.SafeAddress, true
}

// HasSafeAddress returns a boolean if a field has been set.
func (o *SafeWallet) HasSafeAddress() bool {
	if o != nil && !IsNil(o.SafeAddress) {
		return true
	}

	return false
}

// SetSafeAddress gets a reference to the given string and assigns it to the SafeAddress field.
func (o *SafeWallet) SetSafeAddress(v string) {
	o.SafeAddress = &v
}

// GetSigners returns the Signers field value if set, zero value otherwise.
func (o *SafeWallet) GetSigners() []string {
	if o == nil || IsNil(o.Signers) {
		var ret []string
		return ret
	}
	return o.Signers
}

// GetSignersOk returns a tuple with the Signers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SafeWallet) GetSignersOk() ([]string, bool) {
	if o == nil || IsNil(o.Signers) {
		return nil, false
	}
	return o.Signers, true
}

// HasSigners returns a boolean if a field has been set.
func (o *SafeWallet) HasSigners() bool {
	if o != nil && !IsNil(o.Signers) {
		return true
	}

	return false
}

// SetSigners gets a reference to the given []string and assigns it to the Signers field.
func (o *SafeWallet) SetSigners(v []string) {
	o.Signers = v
}

// GetThreshold returns the Threshold field value if set, zero value otherwise.
func (o *SafeWallet) GetThreshold() int32 {
	if o == nil || IsNil(o.Threshold) {
		var ret int32
		return ret
	}
	return *o.Threshold
}

// GetThresholdOk returns a tuple with the Threshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SafeWallet) GetThresholdOk() (*int32, bool) {
	if o == nil || IsNil(o.Threshold) {
		return nil, false
	}
	return o.Threshold, true
}

// HasThreshold returns a boolean if a field has been set.
func (o *SafeWallet) HasThreshold() bool {
	if o != nil && !IsNil(o.Threshold) {
		return true
	}

	return false
}

// SetThreshold gets a reference to the given int32 and assigns it to the Threshold field.
func (o *SafeWallet) SetThreshold(v int32) {
	o.Threshold = &v
}

// GetCoboSafeAddress returns the CoboSafeAddress field value if set, zero value otherwise.
func (o *SafeWallet) GetCoboSafeAddress() string {
	if o == nil || IsNil(o.CoboSafeAddress) {
		var ret string
		return ret
	}
	return *o.CoboSafeAddress
}

// GetCoboSafeAddressOk returns a tuple with the CoboSafeAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SafeWallet) GetCoboSafeAddressOk() (*string, bool) {
	if o == nil || IsNil(o.CoboSafeAddress) {
		return nil, false
	}
	return o.CoboSafeAddress, true
}

// HasCoboSafeAddress returns a boolean if a field has been set.
func (o *SafeWallet) HasCoboSafeAddress() bool {
	if o != nil && !IsNil(o.CoboSafeAddress) {
		return true
	}

	return false
}

// SetCoboSafeAddress gets a reference to the given string and assigns it to the CoboSafeAddress field.
func (o *SafeWallet) SetCoboSafeAddress(v string) {
	o.CoboSafeAddress = &v
}

// GetInitiator returns the Initiator field value if set, zero value otherwise.
func (o *SafeWallet) GetInitiator() SmartContractInitiator {
	if o == nil || IsNil(o.Initiator) {
		var ret SmartContractInitiator
		return ret
	}
	return *o.Initiator
}

// GetInitiatorOk returns a tuple with the Initiator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SafeWallet) GetInitiatorOk() (*SmartContractInitiator, bool) {
	if o == nil || IsNil(o.Initiator) {
		return nil, false
	}
	return o.Initiator, true
}

// HasInitiator returns a boolean if a field has been set.
func (o *SafeWallet) HasInitiator() bool {
	if o != nil && !IsNil(o.Initiator) {
		return true
	}

	return false
}

// SetInitiator gets a reference to the given SmartContractInitiator and assigns it to the Initiator field.
func (o *SafeWallet) SetInitiator(v SmartContractInitiator) {
	o.Initiator = &v
}

func (o SafeWallet) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SafeWallet) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["wallet_id"] = o.WalletId
	toSerialize["wallet_type"] = o.WalletType
	toSerialize["wallet_subtype"] = o.WalletSubtype
	toSerialize["name"] = o.Name
	toSerialize["org_id"] = o.OrgId
	if !IsNil(o.EnableAutoSweep) {
		toSerialize["enable_auto_sweep"] = o.EnableAutoSweep
	}
	if !IsNil(o.ChainId) {
		toSerialize["chain_id"] = o.ChainId
	}
	toSerialize["smart_contract_wallet_type"] = o.SmartContractWalletType
	if !IsNil(o.SafeAddress) {
		toSerialize["safe_address"] = o.SafeAddress
	}
	if !IsNil(o.Signers) {
		toSerialize["signers"] = o.Signers
	}
	if !IsNil(o.Threshold) {
		toSerialize["threshold"] = o.Threshold
	}
	if !IsNil(o.CoboSafeAddress) {
		toSerialize["cobo_safe_address"] = o.CoboSafeAddress
	}
	if !IsNil(o.Initiator) {
		toSerialize["initiator"] = o.Initiator
	}
	return toSerialize, nil
}

func (o *SafeWallet) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"wallet_id",
		"wallet_type",
		"wallet_subtype",
		"name",
		"org_id",
		"smart_contract_wallet_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSafeWallet := _SafeWallet{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSafeWallet)

	if err != nil {
		return err
	}

	*o = SafeWallet(varSafeWallet)

	return err
}

type NullableSafeWallet struct {
	value *SafeWallet
	isSet bool
}

func (v NullableSafeWallet) Get() *SafeWallet {
	return v.value
}

func (v *NullableSafeWallet) Set(val *SafeWallet) {
	v.value = val
	v.isSet = true
}

func (v NullableSafeWallet) IsSet() bool {
	return v.isSet
}

func (v *NullableSafeWallet) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSafeWallet(val *SafeWallet) *NullableSafeWallet {
	return &NullableSafeWallet{value: val, isSet: true}
}

func (v NullableSafeWallet) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSafeWallet) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


