/*
Cobo Wallet as a Service 2.0

Contact: help@cobo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cobo_waas2

import (
	"encoding/json"
)

// checks if the RoleDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RoleDetail{}

// RoleDetail Transaction approval details response schema.
type RoleDetail struct {
	Result *ApprovalTransactionResult `json:"result,omitempty"`
	// The threshold for the transaction approval.
	ReviewThreshold *int32 `json:"review_threshold,omitempty"`
	// The initiator of the transaction.
	Initiator *string `json:"initiator,omitempty"`
	// Indicates whether the transaction approval has been upgraded.
	IsUpgraded *bool `json:"is_upgraded,omitempty"`
	// Time to complete the review.
	CompleteTime *string `json:"complete_time,omitempty"`
	UserDetails []ApprovalUserDetail `json:"user_details,omitempty"`
}

// NewRoleDetail instantiates a new RoleDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoleDetail() *RoleDetail {
	this := RoleDetail{}
	return &this
}

// NewRoleDetailWithDefaults instantiates a new RoleDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoleDetailWithDefaults() *RoleDetail {
	this := RoleDetail{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *RoleDetail) GetResult() ApprovalTransactionResult {
	if o == nil || IsNil(o.Result) {
		var ret ApprovalTransactionResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleDetail) GetResultOk() (*ApprovalTransactionResult, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *RoleDetail) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given ApprovalTransactionResult and assigns it to the Result field.
func (o *RoleDetail) SetResult(v ApprovalTransactionResult) {
	o.Result = &v
}

// GetReviewThreshold returns the ReviewThreshold field value if set, zero value otherwise.
func (o *RoleDetail) GetReviewThreshold() int32 {
	if o == nil || IsNil(o.ReviewThreshold) {
		var ret int32
		return ret
	}
	return *o.ReviewThreshold
}

// GetReviewThresholdOk returns a tuple with the ReviewThreshold field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleDetail) GetReviewThresholdOk() (*int32, bool) {
	if o == nil || IsNil(o.ReviewThreshold) {
		return nil, false
	}
	return o.ReviewThreshold, true
}

// HasReviewThreshold returns a boolean if a field has been set.
func (o *RoleDetail) HasReviewThreshold() bool {
	if o != nil && !IsNil(o.ReviewThreshold) {
		return true
	}

	return false
}

// SetReviewThreshold gets a reference to the given int32 and assigns it to the ReviewThreshold field.
func (o *RoleDetail) SetReviewThreshold(v int32) {
	o.ReviewThreshold = &v
}

// GetInitiator returns the Initiator field value if set, zero value otherwise.
func (o *RoleDetail) GetInitiator() string {
	if o == nil || IsNil(o.Initiator) {
		var ret string
		return ret
	}
	return *o.Initiator
}

// GetInitiatorOk returns a tuple with the Initiator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleDetail) GetInitiatorOk() (*string, bool) {
	if o == nil || IsNil(o.Initiator) {
		return nil, false
	}
	return o.Initiator, true
}

// HasInitiator returns a boolean if a field has been set.
func (o *RoleDetail) HasInitiator() bool {
	if o != nil && !IsNil(o.Initiator) {
		return true
	}

	return false
}

// SetInitiator gets a reference to the given string and assigns it to the Initiator field.
func (o *RoleDetail) SetInitiator(v string) {
	o.Initiator = &v
}

// GetIsUpgraded returns the IsUpgraded field value if set, zero value otherwise.
func (o *RoleDetail) GetIsUpgraded() bool {
	if o == nil || IsNil(o.IsUpgraded) {
		var ret bool
		return ret
	}
	return *o.IsUpgraded
}

// GetIsUpgradedOk returns a tuple with the IsUpgraded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleDetail) GetIsUpgradedOk() (*bool, bool) {
	if o == nil || IsNil(o.IsUpgraded) {
		return nil, false
	}
	return o.IsUpgraded, true
}

// HasIsUpgraded returns a boolean if a field has been set.
func (o *RoleDetail) HasIsUpgraded() bool {
	if o != nil && !IsNil(o.IsUpgraded) {
		return true
	}

	return false
}

// SetIsUpgraded gets a reference to the given bool and assigns it to the IsUpgraded field.
func (o *RoleDetail) SetIsUpgraded(v bool) {
	o.IsUpgraded = &v
}

// GetCompleteTime returns the CompleteTime field value if set, zero value otherwise.
func (o *RoleDetail) GetCompleteTime() string {
	if o == nil || IsNil(o.CompleteTime) {
		var ret string
		return ret
	}
	return *o.CompleteTime
}

// GetCompleteTimeOk returns a tuple with the CompleteTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleDetail) GetCompleteTimeOk() (*string, bool) {
	if o == nil || IsNil(o.CompleteTime) {
		return nil, false
	}
	return o.CompleteTime, true
}

// HasCompleteTime returns a boolean if a field has been set.
func (o *RoleDetail) HasCompleteTime() bool {
	if o != nil && !IsNil(o.CompleteTime) {
		return true
	}

	return false
}

// SetCompleteTime gets a reference to the given string and assigns it to the CompleteTime field.
func (o *RoleDetail) SetCompleteTime(v string) {
	o.CompleteTime = &v
}

// GetUserDetails returns the UserDetails field value if set, zero value otherwise.
func (o *RoleDetail) GetUserDetails() []ApprovalUserDetail {
	if o == nil || IsNil(o.UserDetails) {
		var ret []ApprovalUserDetail
		return ret
	}
	return o.UserDetails
}

// GetUserDetailsOk returns a tuple with the UserDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleDetail) GetUserDetailsOk() ([]ApprovalUserDetail, bool) {
	if o == nil || IsNil(o.UserDetails) {
		return nil, false
	}
	return o.UserDetails, true
}

// HasUserDetails returns a boolean if a field has been set.
func (o *RoleDetail) HasUserDetails() bool {
	if o != nil && !IsNil(o.UserDetails) {
		return true
	}

	return false
}

// SetUserDetails gets a reference to the given []ApprovalUserDetail and assigns it to the UserDetails field.
func (o *RoleDetail) SetUserDetails(v []ApprovalUserDetail) {
	o.UserDetails = v
}

func (o RoleDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RoleDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	if !IsNil(o.ReviewThreshold) {
		toSerialize["review_threshold"] = o.ReviewThreshold
	}
	if !IsNil(o.Initiator) {
		toSerialize["initiator"] = o.Initiator
	}
	if !IsNil(o.IsUpgraded) {
		toSerialize["is_upgraded"] = o.IsUpgraded
	}
	if !IsNil(o.CompleteTime) {
		toSerialize["complete_time"] = o.CompleteTime
	}
	if !IsNil(o.UserDetails) {
		toSerialize["user_details"] = o.UserDetails
	}
	return toSerialize, nil
}

type NullableRoleDetail struct {
	value *RoleDetail
	isSet bool
}

func (v NullableRoleDetail) Get() *RoleDetail {
	return v.value
}

func (v *NullableRoleDetail) Set(val *RoleDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableRoleDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableRoleDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoleDetail(val *RoleDetail) *NullableRoleDetail {
	return &NullableRoleDetail{value: val, isSet: true}
}

func (v NullableRoleDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoleDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


