/*
Cobo Wallet as a Service 2.0

Contact: help@cobo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cobo_waas2

import (
	"encoding/json"
)

// checks if the ListSubscriptionPlans200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListSubscriptionPlans200Response{}

// ListSubscriptionPlans200Response struct for ListSubscriptionPlans200Response
type ListSubscriptionPlans200Response struct {
	Data []PaymentSubscriptionPlan `json:"data,omitempty"`
	Pagination *Pagination `json:"pagination,omitempty"`
}

// NewListSubscriptionPlans200Response instantiates a new ListSubscriptionPlans200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListSubscriptionPlans200Response() *ListSubscriptionPlans200Response {
	this := ListSubscriptionPlans200Response{}
	return &this
}

// NewListSubscriptionPlans200ResponseWithDefaults instantiates a new ListSubscriptionPlans200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListSubscriptionPlans200ResponseWithDefaults() *ListSubscriptionPlans200Response {
	this := ListSubscriptionPlans200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ListSubscriptionPlans200Response) GetData() []PaymentSubscriptionPlan {
	if o == nil || IsNil(o.Data) {
		var ret []PaymentSubscriptionPlan
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListSubscriptionPlans200Response) GetDataOk() ([]PaymentSubscriptionPlan, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ListSubscriptionPlans200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []PaymentSubscriptionPlan and assigns it to the Data field.
func (o *ListSubscriptionPlans200Response) SetData(v []PaymentSubscriptionPlan) {
	o.Data = v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *ListSubscriptionPlans200Response) GetPagination() Pagination {
	if o == nil || IsNil(o.Pagination) {
		var ret Pagination
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListSubscriptionPlans200Response) GetPaginationOk() (*Pagination, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *ListSubscriptionPlans200Response) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given Pagination and assigns it to the Pagination field.
func (o *ListSubscriptionPlans200Response) SetPagination(v Pagination) {
	o.Pagination = &v
}

func (o ListSubscriptionPlans200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListSubscriptionPlans200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}
	return toSerialize, nil
}

type NullableListSubscriptionPlans200Response struct {
	value *ListSubscriptionPlans200Response
	isSet bool
}

func (v NullableListSubscriptionPlans200Response) Get() *ListSubscriptionPlans200Response {
	return v.value
}

func (v *NullableListSubscriptionPlans200Response) Set(val *ListSubscriptionPlans200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListSubscriptionPlans200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListSubscriptionPlans200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListSubscriptionPlans200Response(val *ListSubscriptionPlans200Response) *NullableListSubscriptionPlans200Response {
	return &NullableListSubscriptionPlans200Response{value: val, isSet: true}
}

func (v NullableListSubscriptionPlans200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListSubscriptionPlans200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


