/*
Cobo Wallet as a Service 2.0

Contact: help@cobo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cobo_waas2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RefreshAddressBalancesByToken200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RefreshAddressBalancesByToken200Response{}

// RefreshAddressBalancesByToken200Response struct for RefreshAddressBalancesByToken200Response
type RefreshAddressBalancesByToken200Response struct {
	// Whether the request to refresh address balances has been successfully submitted. - `true`: The request to refresh address balances has been successfully submitted. - `false`: The request to  refresh address balances has not been submitted. 
	Submitted bool `json:"submitted"`
}

type _RefreshAddressBalancesByToken200Response RefreshAddressBalancesByToken200Response

// NewRefreshAddressBalancesByToken200Response instantiates a new RefreshAddressBalancesByToken200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRefreshAddressBalancesByToken200Response(submitted bool) *RefreshAddressBalancesByToken200Response {
	this := RefreshAddressBalancesByToken200Response{}
	this.Submitted = submitted
	return &this
}

// NewRefreshAddressBalancesByToken200ResponseWithDefaults instantiates a new RefreshAddressBalancesByToken200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRefreshAddressBalancesByToken200ResponseWithDefaults() *RefreshAddressBalancesByToken200Response {
	this := RefreshAddressBalancesByToken200Response{}
	return &this
}

// GetSubmitted returns the Submitted field value
func (o *RefreshAddressBalancesByToken200Response) GetSubmitted() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Submitted
}

// GetSubmittedOk returns a tuple with the Submitted field value
// and a boolean to check if the value has been set.
func (o *RefreshAddressBalancesByToken200Response) GetSubmittedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Submitted, true
}

// SetSubmitted sets field value
func (o *RefreshAddressBalancesByToken200Response) SetSubmitted(v bool) {
	o.Submitted = v
}

func (o RefreshAddressBalancesByToken200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RefreshAddressBalancesByToken200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["submitted"] = o.Submitted
	return toSerialize, nil
}

func (o *RefreshAddressBalancesByToken200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"submitted",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRefreshAddressBalancesByToken200Response := _RefreshAddressBalancesByToken200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRefreshAddressBalancesByToken200Response)

	if err != nil {
		return err
	}

	*o = RefreshAddressBalancesByToken200Response(varRefreshAddressBalancesByToken200Response)

	return err
}

type NullableRefreshAddressBalancesByToken200Response struct {
	value *RefreshAddressBalancesByToken200Response
	isSet bool
}

func (v NullableRefreshAddressBalancesByToken200Response) Get() *RefreshAddressBalancesByToken200Response {
	return v.value
}

func (v *NullableRefreshAddressBalancesByToken200Response) Set(val *RefreshAddressBalancesByToken200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableRefreshAddressBalancesByToken200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableRefreshAddressBalancesByToken200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRefreshAddressBalancesByToken200Response(val *RefreshAddressBalancesByToken200Response) *NullableRefreshAddressBalancesByToken200Response {
	return &NullableRefreshAddressBalancesByToken200Response{value: val, isSet: true}
}

func (v NullableRefreshAddressBalancesByToken200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRefreshAddressBalancesByToken200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


