/*
Cobo Wallet as a Service 2.0

Contact: help@cobo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cobo_waas2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateStakeActivityRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateStakeActivityRequest{}

// CreateStakeActivityRequest struct for CreateStakeActivityRequest
type CreateStakeActivityRequest struct {
	// The request ID that is used to track a request. The request ID is provided by you and must be unique within your organization.
	RequestId *string `json:"request_id,omitempty"`
	Source *StakingSource `json:"source,omitempty"`
	// The ID of the staking pool.
	PoolId string `json:"pool_id"`
	// The amount to stake.
	Amount string `json:"amount"`
	Fee TransactionRequestFee `json:"fee"`
	Extra CreateStakeActivityExtra `json:"extra"`
	// The initiator of the staking activity. If you do not specify this property, the WaaS service will automatically designate the API key as the initiator.
	AppInitiator *string `json:"app_initiator,omitempty"`
}

type _CreateStakeActivityRequest CreateStakeActivityRequest

// NewCreateStakeActivityRequest instantiates a new CreateStakeActivityRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateStakeActivityRequest(poolId string, amount string, fee TransactionRequestFee, extra CreateStakeActivityExtra) *CreateStakeActivityRequest {
	this := CreateStakeActivityRequest{}
	this.PoolId = poolId
	this.Amount = amount
	this.Fee = fee
	this.Extra = extra
	return &this
}

// NewCreateStakeActivityRequestWithDefaults instantiates a new CreateStakeActivityRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateStakeActivityRequestWithDefaults() *CreateStakeActivityRequest {
	this := CreateStakeActivityRequest{}
	return &this
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *CreateStakeActivityRequest) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStakeActivityRequest) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *CreateStakeActivityRequest) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *CreateStakeActivityRequest) SetRequestId(v string) {
	o.RequestId = &v
}

// GetSource returns the Source field value if set, zero value otherwise.
func (o *CreateStakeActivityRequest) GetSource() StakingSource {
	if o == nil || IsNil(o.Source) {
		var ret StakingSource
		return ret
	}
	return *o.Source
}

// GetSourceOk returns a tuple with the Source field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStakeActivityRequest) GetSourceOk() (*StakingSource, bool) {
	if o == nil || IsNil(o.Source) {
		return nil, false
	}
	return o.Source, true
}

// HasSource returns a boolean if a field has been set.
func (o *CreateStakeActivityRequest) HasSource() bool {
	if o != nil && !IsNil(o.Source) {
		return true
	}

	return false
}

// SetSource gets a reference to the given StakingSource and assigns it to the Source field.
func (o *CreateStakeActivityRequest) SetSource(v StakingSource) {
	o.Source = &v
}

// GetPoolId returns the PoolId field value
func (o *CreateStakeActivityRequest) GetPoolId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PoolId
}

// GetPoolIdOk returns a tuple with the PoolId field value
// and a boolean to check if the value has been set.
func (o *CreateStakeActivityRequest) GetPoolIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PoolId, true
}

// SetPoolId sets field value
func (o *CreateStakeActivityRequest) SetPoolId(v string) {
	o.PoolId = v
}

// GetAmount returns the Amount field value
func (o *CreateStakeActivityRequest) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *CreateStakeActivityRequest) GetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *CreateStakeActivityRequest) SetAmount(v string) {
	o.Amount = v
}

// GetFee returns the Fee field value
func (o *CreateStakeActivityRequest) GetFee() TransactionRequestFee {
	if o == nil {
		var ret TransactionRequestFee
		return ret
	}

	return o.Fee
}

// GetFeeOk returns a tuple with the Fee field value
// and a boolean to check if the value has been set.
func (o *CreateStakeActivityRequest) GetFeeOk() (*TransactionRequestFee, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Fee, true
}

// SetFee sets field value
func (o *CreateStakeActivityRequest) SetFee(v TransactionRequestFee) {
	o.Fee = v
}

// GetExtra returns the Extra field value
func (o *CreateStakeActivityRequest) GetExtra() CreateStakeActivityExtra {
	if o == nil {
		var ret CreateStakeActivityExtra
		return ret
	}

	return o.Extra
}

// GetExtraOk returns a tuple with the Extra field value
// and a boolean to check if the value has been set.
func (o *CreateStakeActivityRequest) GetExtraOk() (*CreateStakeActivityExtra, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Extra, true
}

// SetExtra sets field value
func (o *CreateStakeActivityRequest) SetExtra(v CreateStakeActivityExtra) {
	o.Extra = v
}

// GetAppInitiator returns the AppInitiator field value if set, zero value otherwise.
func (o *CreateStakeActivityRequest) GetAppInitiator() string {
	if o == nil || IsNil(o.AppInitiator) {
		var ret string
		return ret
	}
	return *o.AppInitiator
}

// GetAppInitiatorOk returns a tuple with the AppInitiator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStakeActivityRequest) GetAppInitiatorOk() (*string, bool) {
	if o == nil || IsNil(o.AppInitiator) {
		return nil, false
	}
	return o.AppInitiator, true
}

// HasAppInitiator returns a boolean if a field has been set.
func (o *CreateStakeActivityRequest) HasAppInitiator() bool {
	if o != nil && !IsNil(o.AppInitiator) {
		return true
	}

	return false
}

// SetAppInitiator gets a reference to the given string and assigns it to the AppInitiator field.
func (o *CreateStakeActivityRequest) SetAppInitiator(v string) {
	o.AppInitiator = &v
}

func (o CreateStakeActivityRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateStakeActivityRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RequestId) {
		toSerialize["request_id"] = o.RequestId
	}
	if !IsNil(o.Source) {
		toSerialize["source"] = o.Source
	}
	toSerialize["pool_id"] = o.PoolId
	toSerialize["amount"] = o.Amount
	toSerialize["fee"] = o.Fee
	toSerialize["extra"] = o.Extra
	if !IsNil(o.AppInitiator) {
		toSerialize["app_initiator"] = o.AppInitiator
	}
	return toSerialize, nil
}

func (o *CreateStakeActivityRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"pool_id",
		"amount",
		"fee",
		"extra",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateStakeActivityRequest := _CreateStakeActivityRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateStakeActivityRequest)

	if err != nil {
		return err
	}

	*o = CreateStakeActivityRequest(varCreateStakeActivityRequest)

	return err
}

type NullableCreateStakeActivityRequest struct {
	value *CreateStakeActivityRequest
	isSet bool
}

func (v NullableCreateStakeActivityRequest) Get() *CreateStakeActivityRequest {
	return v.value
}

func (v *NullableCreateStakeActivityRequest) Set(val *CreateStakeActivityRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateStakeActivityRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateStakeActivityRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateStakeActivityRequest(val *CreateStakeActivityRequest) *NullableCreateStakeActivityRequest {
	return &NullableCreateStakeActivityRequest{value: val, isSet: true}
}

func (v NullableCreateStakeActivityRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateStakeActivityRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


