/*
Cobo Wallet as a Service 2.0

Contact: help@cobo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cobo_waas2

import (
	"encoding/json"
)

// checks if the PreCheck type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PreCheck{}

// PreCheck Some validation settings for creating a transaction.
type PreCheck struct {
	// Selection to skip verification.
	SkipChecks []SkipCheckType `json:"skip_checks,omitempty"`
}

// NewPreCheck instantiates a new PreCheck object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPreCheck() *PreCheck {
	this := PreCheck{}
	return &this
}

// NewPreCheckWithDefaults instantiates a new PreCheck object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPreCheckWithDefaults() *PreCheck {
	this := PreCheck{}
	return &this
}

// GetSkipChecks returns the SkipChecks field value if set, zero value otherwise.
func (o *PreCheck) GetSkipChecks() []SkipCheckType {
	if o == nil || IsNil(o.SkipChecks) {
		var ret []SkipCheckType
		return ret
	}
	return o.SkipChecks
}

// GetSkipChecksOk returns a tuple with the SkipChecks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PreCheck) GetSkipChecksOk() ([]SkipCheckType, bool) {
	if o == nil || IsNil(o.SkipChecks) {
		return nil, false
	}
	return o.SkipChecks, true
}

// HasSkipChecks returns a boolean if a field has been set.
func (o *PreCheck) HasSkipChecks() bool {
	if o != nil && !IsNil(o.SkipChecks) {
		return true
	}

	return false
}

// SetSkipChecks gets a reference to the given []SkipCheckType and assigns it to the SkipChecks field.
func (o *PreCheck) SetSkipChecks(v []SkipCheckType) {
	o.SkipChecks = v
}

func (o PreCheck) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PreCheck) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SkipChecks) {
		toSerialize["skip_checks"] = o.SkipChecks
	}
	return toSerialize, nil
}

type NullablePreCheck struct {
	value *PreCheck
	isSet bool
}

func (v NullablePreCheck) Get() *PreCheck {
	return v.value
}

func (v *NullablePreCheck) Set(val *PreCheck) {
	v.value = val
	v.isSet = true
}

func (v NullablePreCheck) IsSet() bool {
	return v.isSet
}

func (v *NullablePreCheck) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePreCheck(val *PreCheck) *NullablePreCheck {
	return &NullablePreCheck{value: val, isSet: true}
}

func (v NullablePreCheck) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePreCheck) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


