/*
Cobo Wallet as a Service 2.0

Contact: help@cobo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cobo_waas2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the KyaRiskAssessment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KyaRiskAssessment{}

// KyaRiskAssessment The risk assessment information for the screened address. Only returned when status is 'Screened'.
type KyaRiskAssessment struct {
	Level KyaRiskLevel `json:"level"`
	// A brief summary of the risk assessment.
	Summary *string `json:"summary,omitempty"`
	// Detailed risk category assessments.
	Details []KyaRiskDetail `json:"details,omitempty"`
}

type _KyaRiskAssessment KyaRiskAssessment

// NewKyaRiskAssessment instantiates a new KyaRiskAssessment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKyaRiskAssessment(level KyaRiskLevel) *KyaRiskAssessment {
	this := KyaRiskAssessment{}
	this.Level = level
	return &this
}

// NewKyaRiskAssessmentWithDefaults instantiates a new KyaRiskAssessment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKyaRiskAssessmentWithDefaults() *KyaRiskAssessment {
	this := KyaRiskAssessment{}
	return &this
}

// GetLevel returns the Level field value
func (o *KyaRiskAssessment) GetLevel() KyaRiskLevel {
	if o == nil {
		var ret KyaRiskLevel
		return ret
	}

	return o.Level
}

// GetLevelOk returns a tuple with the Level field value
// and a boolean to check if the value has been set.
func (o *KyaRiskAssessment) GetLevelOk() (*KyaRiskLevel, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Level, true
}

// SetLevel sets field value
func (o *KyaRiskAssessment) SetLevel(v KyaRiskLevel) {
	o.Level = v
}

// GetSummary returns the Summary field value if set, zero value otherwise.
func (o *KyaRiskAssessment) GetSummary() string {
	if o == nil || IsNil(o.Summary) {
		var ret string
		return ret
	}
	return *o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KyaRiskAssessment) GetSummaryOk() (*string, bool) {
	if o == nil || IsNil(o.Summary) {
		return nil, false
	}
	return o.Summary, true
}

// HasSummary returns a boolean if a field has been set.
func (o *KyaRiskAssessment) HasSummary() bool {
	if o != nil && !IsNil(o.Summary) {
		return true
	}

	return false
}

// SetSummary gets a reference to the given string and assigns it to the Summary field.
func (o *KyaRiskAssessment) SetSummary(v string) {
	o.Summary = &v
}

// GetDetails returns the Details field value if set, zero value otherwise.
func (o *KyaRiskAssessment) GetDetails() []KyaRiskDetail {
	if o == nil || IsNil(o.Details) {
		var ret []KyaRiskDetail
		return ret
	}
	return o.Details
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KyaRiskAssessment) GetDetailsOk() ([]KyaRiskDetail, bool) {
	if o == nil || IsNil(o.Details) {
		return nil, false
	}
	return o.Details, true
}

// HasDetails returns a boolean if a field has been set.
func (o *KyaRiskAssessment) HasDetails() bool {
	if o != nil && !IsNil(o.Details) {
		return true
	}

	return false
}

// SetDetails gets a reference to the given []KyaRiskDetail and assigns it to the Details field.
func (o *KyaRiskAssessment) SetDetails(v []KyaRiskDetail) {
	o.Details = v
}

func (o KyaRiskAssessment) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KyaRiskAssessment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["level"] = o.Level
	if !IsNil(o.Summary) {
		toSerialize["summary"] = o.Summary
	}
	if !IsNil(o.Details) {
		toSerialize["details"] = o.Details
	}
	return toSerialize, nil
}

func (o *KyaRiskAssessment) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"level",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKyaRiskAssessment := _KyaRiskAssessment{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varKyaRiskAssessment)

	if err != nil {
		return err
	}

	*o = KyaRiskAssessment(varKyaRiskAssessment)

	return err
}

type NullableKyaRiskAssessment struct {
	value *KyaRiskAssessment
	isSet bool
}

func (v NullableKyaRiskAssessment) Get() *KyaRiskAssessment {
	return v.value
}

func (v *NullableKyaRiskAssessment) Set(val *KyaRiskAssessment) {
	v.value = val
	v.isSet = true
}

func (v NullableKyaRiskAssessment) IsSet() bool {
	return v.isSet
}

func (v *NullableKyaRiskAssessment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKyaRiskAssessment(val *KyaRiskAssessment) *NullableKyaRiskAssessment {
	return &NullableKyaRiskAssessment{value: val, isSet: true}
}

func (v NullableKyaRiskAssessment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKyaRiskAssessment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


