/*
Cobo Wallet as a Service 2.0

Contact: help@cobo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cobo_waas2

import (
	"encoding/json"
	"os"
	"bytes"
	"fmt"
)

// checks if the UploadPaymentFileRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadPaymentFileRequest{}

// UploadPaymentFileRequest struct for UploadPaymentFileRequest
type UploadPaymentFileRequest struct {
	// The file to upload.
	File *os.File `json:"file"`
}

type _UploadPaymentFileRequest UploadPaymentFileRequest

// NewUploadPaymentFileRequest instantiates a new UploadPaymentFileRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadPaymentFileRequest(file *os.File) *UploadPaymentFileRequest {
	this := UploadPaymentFileRequest{}
	this.File = file
	return &this
}

// NewUploadPaymentFileRequestWithDefaults instantiates a new UploadPaymentFileRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadPaymentFileRequestWithDefaults() *UploadPaymentFileRequest {
	this := UploadPaymentFileRequest{}
	return &this
}

// GetFile returns the File field value
func (o *UploadPaymentFileRequest) GetFile() *os.File {
	if o == nil {
		var ret *os.File
		return ret
	}

	return o.File
}

// GetFileOk returns a tuple with the File field value
// and a boolean to check if the value has been set.
func (o *UploadPaymentFileRequest) GetFileOk() (**os.File, bool) {
	if o == nil {
		return nil, false
	}
	return &o.File, true
}

// SetFile sets field value
func (o *UploadPaymentFileRequest) SetFile(v *os.File) {
	o.File = v
}

func (o UploadPaymentFileRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadPaymentFileRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["file"] = o.File
	return toSerialize, nil
}

func (o *UploadPaymentFileRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"file",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUploadPaymentFileRequest := _UploadPaymentFileRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUploadPaymentFileRequest)

	if err != nil {
		return err
	}

	*o = UploadPaymentFileRequest(varUploadPaymentFileRequest)

	return err
}

type NullableUploadPaymentFileRequest struct {
	value *UploadPaymentFileRequest
	isSet bool
}

func (v NullableUploadPaymentFileRequest) Get() *UploadPaymentFileRequest {
	return v.value
}

func (v *NullableUploadPaymentFileRequest) Set(val *UploadPaymentFileRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadPaymentFileRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadPaymentFileRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadPaymentFileRequest(val *UploadPaymentFileRequest) *NullableUploadPaymentFileRequest {
	return &NullableUploadPaymentFileRequest{value: val, isSet: true}
}

func (v NullableUploadPaymentFileRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadPaymentFileRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


