/*
Cobo Wallet as a Service 2.0

Contact: help@cobo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cobo_waas2

import (
	"encoding/json"
	"fmt"
)

// PayoutFeeData - struct for PayoutFeeData
type PayoutFeeData struct {
	TransactionRequestEvmEip1559Fee *TransactionRequestEvmEip1559Fee
	TransactionRequestEvmLegacyFee *TransactionRequestEvmLegacyFee
	TransactionRequestFixedFee *TransactionRequestFixedFee
	TransactionRequestUtxoFee *TransactionRequestUtxoFee
}

// TransactionRequestEvmEip1559FeeAsPayoutFeeData is a convenience function that returns TransactionRequestEvmEip1559Fee wrapped in PayoutFeeData
func TransactionRequestEvmEip1559FeeAsPayoutFeeData(v *TransactionRequestEvmEip1559Fee) PayoutFeeData {
	return PayoutFeeData{
		TransactionRequestEvmEip1559Fee: v,
	}
}

// TransactionRequestEvmLegacyFeeAsPayoutFeeData is a convenience function that returns TransactionRequestEvmLegacyFee wrapped in PayoutFeeData
func TransactionRequestEvmLegacyFeeAsPayoutFeeData(v *TransactionRequestEvmLegacyFee) PayoutFeeData {
	return PayoutFeeData{
		TransactionRequestEvmLegacyFee: v,
	}
}

// TransactionRequestFixedFeeAsPayoutFeeData is a convenience function that returns TransactionRequestFixedFee wrapped in PayoutFeeData
func TransactionRequestFixedFeeAsPayoutFeeData(v *TransactionRequestFixedFee) PayoutFeeData {
	return PayoutFeeData{
		TransactionRequestFixedFee: v,
	}
}

// TransactionRequestUtxoFeeAsPayoutFeeData is a convenience function that returns TransactionRequestUtxoFee wrapped in PayoutFeeData
func TransactionRequestUtxoFeeAsPayoutFeeData(v *TransactionRequestUtxoFee) PayoutFeeData {
	return PayoutFeeData{
		TransactionRequestUtxoFee: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *PayoutFeeData) UnmarshalJSON(data []byte) error {
	var err error
	// use discriminator value to speed up the lookup
	var jsonDict map[string]interface{}
	err = newStrictDecoder(data).Decode(&jsonDict)
	if err != nil {
		return fmt.Errorf("failed to unmarshal JSON into map for the discriminator lookup")
	}

	// check if the discriminator value is 'EVM_EIP_1559'
	if jsonDict["fee_type"] == "EVM_EIP_1559" {
		// try to unmarshal JSON data into TransactionRequestEvmEip1559Fee
		err = json.Unmarshal(data, &dst.TransactionRequestEvmEip1559Fee)
		if err == nil {
			return nil // data stored in dst.TransactionRequestEvmEip1559Fee, return on the first match
		} else {
			dst.TransactionRequestEvmEip1559Fee = nil
			return fmt.Errorf("failed to unmarshal PayoutFeeData as TransactionRequestEvmEip1559Fee: %s", err.Error())
		}
	}

	// check if the discriminator value is 'EVM_Legacy'
	if jsonDict["fee_type"] == "EVM_Legacy" {
		// try to unmarshal JSON data into TransactionRequestEvmLegacyFee
		err = json.Unmarshal(data, &dst.TransactionRequestEvmLegacyFee)
		if err == nil {
			return nil // data stored in dst.TransactionRequestEvmLegacyFee, return on the first match
		} else {
			dst.TransactionRequestEvmLegacyFee = nil
			return fmt.Errorf("failed to unmarshal PayoutFeeData as TransactionRequestEvmLegacyFee: %s", err.Error())
		}
	}

	// check if the discriminator value is 'Fixed'
	if jsonDict["fee_type"] == "Fixed" {
		// try to unmarshal JSON data into TransactionRequestFixedFee
		err = json.Unmarshal(data, &dst.TransactionRequestFixedFee)
		if err == nil {
			return nil // data stored in dst.TransactionRequestFixedFee, return on the first match
		} else {
			dst.TransactionRequestFixedFee = nil
			return fmt.Errorf("failed to unmarshal PayoutFeeData as TransactionRequestFixedFee: %s", err.Error())
		}
	}

	// check if the discriminator value is 'UTXO'
	if jsonDict["fee_type"] == "UTXO" {
		// try to unmarshal JSON data into TransactionRequestUtxoFee
		err = json.Unmarshal(data, &dst.TransactionRequestUtxoFee)
		if err == nil {
			return nil // data stored in dst.TransactionRequestUtxoFee, return on the first match
		} else {
			dst.TransactionRequestUtxoFee = nil
			return fmt.Errorf("failed to unmarshal PayoutFeeData as TransactionRequestUtxoFee: %s", err.Error())
		}
	}

	// check if the discriminator value is 'TransactionRequestEvmEip1559Fee'
	if jsonDict["fee_type"] == "TransactionRequestEvmEip1559Fee" {
		// try to unmarshal JSON data into TransactionRequestEvmEip1559Fee
		err = json.Unmarshal(data, &dst.TransactionRequestEvmEip1559Fee)
		if err == nil {
			return nil // data stored in dst.TransactionRequestEvmEip1559Fee, return on the first match
		} else {
			dst.TransactionRequestEvmEip1559Fee = nil
			return fmt.Errorf("failed to unmarshal PayoutFeeData as TransactionRequestEvmEip1559Fee: %s", err.Error())
		}
	}

	// check if the discriminator value is 'TransactionRequestEvmLegacyFee'
	if jsonDict["fee_type"] == "TransactionRequestEvmLegacyFee" {
		// try to unmarshal JSON data into TransactionRequestEvmLegacyFee
		err = json.Unmarshal(data, &dst.TransactionRequestEvmLegacyFee)
		if err == nil {
			return nil // data stored in dst.TransactionRequestEvmLegacyFee, return on the first match
		} else {
			dst.TransactionRequestEvmLegacyFee = nil
			return fmt.Errorf("failed to unmarshal PayoutFeeData as TransactionRequestEvmLegacyFee: %s", err.Error())
		}
	}

	// check if the discriminator value is 'TransactionRequestFixedFee'
	if jsonDict["fee_type"] == "TransactionRequestFixedFee" {
		// try to unmarshal JSON data into TransactionRequestFixedFee
		err = json.Unmarshal(data, &dst.TransactionRequestFixedFee)
		if err == nil {
			return nil // data stored in dst.TransactionRequestFixedFee, return on the first match
		} else {
			dst.TransactionRequestFixedFee = nil
			return fmt.Errorf("failed to unmarshal PayoutFeeData as TransactionRequestFixedFee: %s", err.Error())
		}
	}

	// check if the discriminator value is 'TransactionRequestUtxoFee'
	if jsonDict["fee_type"] == "TransactionRequestUtxoFee" {
		// try to unmarshal JSON data into TransactionRequestUtxoFee
		err = json.Unmarshal(data, &dst.TransactionRequestUtxoFee)
		if err == nil {
			return nil // data stored in dst.TransactionRequestUtxoFee, return on the first match
		} else {
			dst.TransactionRequestUtxoFee = nil
			return fmt.Errorf("failed to unmarshal PayoutFeeData as TransactionRequestUtxoFee: %s", err.Error())
		}
	}

	return nil
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PayoutFeeData) MarshalJSON() ([]byte, error) {
	if src.TransactionRequestEvmEip1559Fee != nil {
		return json.Marshal(&src.TransactionRequestEvmEip1559Fee)
	}

	if src.TransactionRequestEvmLegacyFee != nil {
		return json.Marshal(&src.TransactionRequestEvmLegacyFee)
	}

	if src.TransactionRequestFixedFee != nil {
		return json.Marshal(&src.TransactionRequestFixedFee)
	}

	if src.TransactionRequestUtxoFee != nil {
		return json.Marshal(&src.TransactionRequestUtxoFee)
	}

	return []byte(`{}`), nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PayoutFeeData) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.TransactionRequestEvmEip1559Fee != nil {
		return obj.TransactionRequestEvmEip1559Fee
	}

	if obj.TransactionRequestEvmLegacyFee != nil {
		return obj.TransactionRequestEvmLegacyFee
	}

	if obj.TransactionRequestFixedFee != nil {
		return obj.TransactionRequestFixedFee
	}

	if obj.TransactionRequestUtxoFee != nil {
		return obj.TransactionRequestUtxoFee
	}

	// all schemas are nil
	return nil
}

type NullablePayoutFeeData struct {
	value *PayoutFeeData
	isSet bool
}

func (v NullablePayoutFeeData) Get() *PayoutFeeData {
	return v.value
}

func (v *NullablePayoutFeeData) Set(val *PayoutFeeData) {
	v.value = val
	v.isSet = true
}

func (v NullablePayoutFeeData) IsSet() bool {
	return v.isSet
}

func (v *NullablePayoutFeeData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePayoutFeeData(val *PayoutFeeData) *NullablePayoutFeeData {
	return &NullablePayoutFeeData{value: val, isSet: true}
}

func (v NullablePayoutFeeData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePayoutFeeData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


