/*
Cobo Wallet as a Service 2.0

Contact: help@cobo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cobo_waas2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PaymentRefundEventData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaymentRefundEventData{}

// PaymentRefundEventData struct for PaymentRefundEventData
type PaymentRefundEventData struct {
	//  The data type of the event. - `Transaction`: The transaction event data. - `TSSRequest`: The TSS request event data. - `Addresses`: The addresses event data. - `WalletInfo`: The wallet information event data. - `MPCVault`: The MPC vault event data. - `Chains`: The enabled chain event data. - `Tokens`: The enabled token event data. - `TokenListing`: The token listing event data.        - `PaymentOrder`: The payment order event data. - `PaymentRefund`: The payment refund event data. - `PaymentSettlement`: The payment settlement event data. - `PaymentTransaction`: The payment transaction event data. - `PaymentAddressUpdate`: The top-up address update event data. - `PaymentPayout`: The payment payout event data. - `PaymentBulkSend`: The payment bulk send event data. - `BalanceUpdateInfo`: The balance update event data. - `SuspendedToken`: The token suspension event data. - `ComplianceDisposition`: The compliance disposition event data. - `ComplianceKytScreenings`: The compliance KYT screenings event data. - `ComplianceKyaScreenings`: The compliance KYA screenings event data.
	DataType string `json:"data_type"`
	// The request ID provided by you when creating the refund request.
	RequestId *string `json:"request_id,omitempty"`
	// The refund order ID.
	RefundId string `json:"refund_id"`
	// The ID of the pay-in order corresponding to this refund.
	OrderId *string `json:"order_id,omitempty"`
	// The merchant ID.
	MerchantId *string `json:"merchant_id,omitempty"`
	// The ID of the cryptocurrency used for refund.
	TokenId string `json:"token_id"`
	// The ID of the blockchain network on which the refund transaction occurs.
	ChainId string `json:"chain_id"`
	// The amount in cryptocurrency to be returned for this refund order.
	Amount string `json:"amount"`
	// The recipient's wallet address where the refund will be sent.
	ToAddress string `json:"to_address"`
	Status RefundStatus `json:"status"`
	RefundType *RefundType `json:"refund_type,omitempty"`
	// The creation time of the refund order, represented as a UNIX timestamp in seconds.
	CreatedTimestamp *int32 `json:"created_timestamp,omitempty"`
	// The last update time of the refund order, represented as a UNIX timestamp in seconds.
	UpdatedTimestamp *int32 `json:"updated_timestamp,omitempty"`
	//  The initiator of this settlement request. Can return either an API key or the Payments App's ID.  - Format `api_key_<API_KEY>`: Indicates the settlement request was initiated via the Payments API using the API key. - Format `app_<APP_ID>`: Indicates the settlement request was initiated through the Payments App using the App ID. 
	Initiator *string `json:"initiator,omitempty"`
	// An array of transactions associated with this refund order. Each transaction represents a separate blockchain operation related to the refund process.
	Transactions []PaymentTransaction `json:"transactions,omitempty"`
	// Whether to charge developer fee to the merchant for the refund.    - `true`: The fee amount (specified in `merchant_fee_amount`) will be deducted from the merchant's balance and added to the developer's balance    - `false`: The merchant is not charged any developer fee. 
	ChargeMerchantFee *bool `json:"charge_merchant_fee,omitempty"`
	// The developer fee amount to charge the merchant, denominated in the cryptocurrency specified by `merchant_fee_token_id`. This is only applicable if `charge_merchant_fee` is set to `true`.
	MerchantFeeAmount *string `json:"merchant_fee_amount,omitempty"`
	// The ID of the cryptocurrency used for the developer fee. This is only applicable if `charge_merchant_fee` is set to true.
	MerchantFeeTokenId *string `json:"merchant_fee_token_id,omitempty"`
	CommissionFee *CommissionFee `json:"commission_fee,omitempty"`
}

type _PaymentRefundEventData PaymentRefundEventData

// NewPaymentRefundEventData instantiates a new PaymentRefundEventData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaymentRefundEventData(dataType string, refundId string, tokenId string, chainId string, amount string, toAddress string, status RefundStatus) *PaymentRefundEventData {
	this := PaymentRefundEventData{}
	this.DataType = dataType
	this.RefundId = refundId
	this.TokenId = tokenId
	this.ChainId = chainId
	this.Amount = amount
	this.ToAddress = toAddress
	this.Status = status
	return &this
}

// NewPaymentRefundEventDataWithDefaults instantiates a new PaymentRefundEventData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaymentRefundEventDataWithDefaults() *PaymentRefundEventData {
	this := PaymentRefundEventData{}
	return &this
}

// GetDataType returns the DataType field value
func (o *PaymentRefundEventData) GetDataType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DataType
}

// GetDataTypeOk returns a tuple with the DataType field value
// and a boolean to check if the value has been set.
func (o *PaymentRefundEventData) GetDataTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DataType, true
}

// SetDataType sets field value
func (o *PaymentRefundEventData) SetDataType(v string) {
	o.DataType = v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *PaymentRefundEventData) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentRefundEventData) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *PaymentRefundEventData) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *PaymentRefundEventData) SetRequestId(v string) {
	o.RequestId = &v
}

// GetRefundId returns the RefundId field value
func (o *PaymentRefundEventData) GetRefundId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RefundId
}

// GetRefundIdOk returns a tuple with the RefundId field value
// and a boolean to check if the value has been set.
func (o *PaymentRefundEventData) GetRefundIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RefundId, true
}

// SetRefundId sets field value
func (o *PaymentRefundEventData) SetRefundId(v string) {
	o.RefundId = v
}

// GetOrderId returns the OrderId field value if set, zero value otherwise.
func (o *PaymentRefundEventData) GetOrderId() string {
	if o == nil || IsNil(o.OrderId) {
		var ret string
		return ret
	}
	return *o.OrderId
}

// GetOrderIdOk returns a tuple with the OrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentRefundEventData) GetOrderIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrderId) {
		return nil, false
	}
	return o.OrderId, true
}

// HasOrderId returns a boolean if a field has been set.
func (o *PaymentRefundEventData) HasOrderId() bool {
	if o != nil && !IsNil(o.OrderId) {
		return true
	}

	return false
}

// SetOrderId gets a reference to the given string and assigns it to the OrderId field.
func (o *PaymentRefundEventData) SetOrderId(v string) {
	o.OrderId = &v
}

// GetMerchantId returns the MerchantId field value if set, zero value otherwise.
func (o *PaymentRefundEventData) GetMerchantId() string {
	if o == nil || IsNil(o.MerchantId) {
		var ret string
		return ret
	}
	return *o.MerchantId
}

// GetMerchantIdOk returns a tuple with the MerchantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentRefundEventData) GetMerchantIdOk() (*string, bool) {
	if o == nil || IsNil(o.MerchantId) {
		return nil, false
	}
	return o.MerchantId, true
}

// HasMerchantId returns a boolean if a field has been set.
func (o *PaymentRefundEventData) HasMerchantId() bool {
	if o != nil && !IsNil(o.MerchantId) {
		return true
	}

	return false
}

// SetMerchantId gets a reference to the given string and assigns it to the MerchantId field.
func (o *PaymentRefundEventData) SetMerchantId(v string) {
	o.MerchantId = &v
}

// GetTokenId returns the TokenId field value
func (o *PaymentRefundEventData) GetTokenId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenId
}

// GetTokenIdOk returns a tuple with the TokenId field value
// and a boolean to check if the value has been set.
func (o *PaymentRefundEventData) GetTokenIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenId, true
}

// SetTokenId sets field value
func (o *PaymentRefundEventData) SetTokenId(v string) {
	o.TokenId = v
}

// GetChainId returns the ChainId field value
func (o *PaymentRefundEventData) GetChainId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChainId
}

// GetChainIdOk returns a tuple with the ChainId field value
// and a boolean to check if the value has been set.
func (o *PaymentRefundEventData) GetChainIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChainId, true
}

// SetChainId sets field value
func (o *PaymentRefundEventData) SetChainId(v string) {
	o.ChainId = v
}

// GetAmount returns the Amount field value
func (o *PaymentRefundEventData) GetAmount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *PaymentRefundEventData) GetAmountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *PaymentRefundEventData) SetAmount(v string) {
	o.Amount = v
}

// GetToAddress returns the ToAddress field value
func (o *PaymentRefundEventData) GetToAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ToAddress
}

// GetToAddressOk returns a tuple with the ToAddress field value
// and a boolean to check if the value has been set.
func (o *PaymentRefundEventData) GetToAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ToAddress, true
}

// SetToAddress sets field value
func (o *PaymentRefundEventData) SetToAddress(v string) {
	o.ToAddress = v
}

// GetStatus returns the Status field value
func (o *PaymentRefundEventData) GetStatus() RefundStatus {
	if o == nil {
		var ret RefundStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *PaymentRefundEventData) GetStatusOk() (*RefundStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *PaymentRefundEventData) SetStatus(v RefundStatus) {
	o.Status = v
}

// GetRefundType returns the RefundType field value if set, zero value otherwise.
func (o *PaymentRefundEventData) GetRefundType() RefundType {
	if o == nil || IsNil(o.RefundType) {
		var ret RefundType
		return ret
	}
	return *o.RefundType
}

// GetRefundTypeOk returns a tuple with the RefundType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentRefundEventData) GetRefundTypeOk() (*RefundType, bool) {
	if o == nil || IsNil(o.RefundType) {
		return nil, false
	}
	return o.RefundType, true
}

// HasRefundType returns a boolean if a field has been set.
func (o *PaymentRefundEventData) HasRefundType() bool {
	if o != nil && !IsNil(o.RefundType) {
		return true
	}

	return false
}

// SetRefundType gets a reference to the given RefundType and assigns it to the RefundType field.
func (o *PaymentRefundEventData) SetRefundType(v RefundType) {
	o.RefundType = &v
}

// GetCreatedTimestamp returns the CreatedTimestamp field value if set, zero value otherwise.
func (o *PaymentRefundEventData) GetCreatedTimestamp() int32 {
	if o == nil || IsNil(o.CreatedTimestamp) {
		var ret int32
		return ret
	}
	return *o.CreatedTimestamp
}

// GetCreatedTimestampOk returns a tuple with the CreatedTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentRefundEventData) GetCreatedTimestampOk() (*int32, bool) {
	if o == nil || IsNil(o.CreatedTimestamp) {
		return nil, false
	}
	return o.CreatedTimestamp, true
}

// HasCreatedTimestamp returns a boolean if a field has been set.
func (o *PaymentRefundEventData) HasCreatedTimestamp() bool {
	if o != nil && !IsNil(o.CreatedTimestamp) {
		return true
	}

	return false
}

// SetCreatedTimestamp gets a reference to the given int32 and assigns it to the CreatedTimestamp field.
func (o *PaymentRefundEventData) SetCreatedTimestamp(v int32) {
	o.CreatedTimestamp = &v
}

// GetUpdatedTimestamp returns the UpdatedTimestamp field value if set, zero value otherwise.
func (o *PaymentRefundEventData) GetUpdatedTimestamp() int32 {
	if o == nil || IsNil(o.UpdatedTimestamp) {
		var ret int32
		return ret
	}
	return *o.UpdatedTimestamp
}

// GetUpdatedTimestampOk returns a tuple with the UpdatedTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentRefundEventData) GetUpdatedTimestampOk() (*int32, bool) {
	if o == nil || IsNil(o.UpdatedTimestamp) {
		return nil, false
	}
	return o.UpdatedTimestamp, true
}

// HasUpdatedTimestamp returns a boolean if a field has been set.
func (o *PaymentRefundEventData) HasUpdatedTimestamp() bool {
	if o != nil && !IsNil(o.UpdatedTimestamp) {
		return true
	}

	return false
}

// SetUpdatedTimestamp gets a reference to the given int32 and assigns it to the UpdatedTimestamp field.
func (o *PaymentRefundEventData) SetUpdatedTimestamp(v int32) {
	o.UpdatedTimestamp = &v
}

// GetInitiator returns the Initiator field value if set, zero value otherwise.
func (o *PaymentRefundEventData) GetInitiator() string {
	if o == nil || IsNil(o.Initiator) {
		var ret string
		return ret
	}
	return *o.Initiator
}

// GetInitiatorOk returns a tuple with the Initiator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentRefundEventData) GetInitiatorOk() (*string, bool) {
	if o == nil || IsNil(o.Initiator) {
		return nil, false
	}
	return o.Initiator, true
}

// HasInitiator returns a boolean if a field has been set.
func (o *PaymentRefundEventData) HasInitiator() bool {
	if o != nil && !IsNil(o.Initiator) {
		return true
	}

	return false
}

// SetInitiator gets a reference to the given string and assigns it to the Initiator field.
func (o *PaymentRefundEventData) SetInitiator(v string) {
	o.Initiator = &v
}

// GetTransactions returns the Transactions field value if set, zero value otherwise.
func (o *PaymentRefundEventData) GetTransactions() []PaymentTransaction {
	if o == nil || IsNil(o.Transactions) {
		var ret []PaymentTransaction
		return ret
	}
	return o.Transactions
}

// GetTransactionsOk returns a tuple with the Transactions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentRefundEventData) GetTransactionsOk() ([]PaymentTransaction, bool) {
	if o == nil || IsNil(o.Transactions) {
		return nil, false
	}
	return o.Transactions, true
}

// HasTransactions returns a boolean if a field has been set.
func (o *PaymentRefundEventData) HasTransactions() bool {
	if o != nil && !IsNil(o.Transactions) {
		return true
	}

	return false
}

// SetTransactions gets a reference to the given []PaymentTransaction and assigns it to the Transactions field.
func (o *PaymentRefundEventData) SetTransactions(v []PaymentTransaction) {
	o.Transactions = v
}

// GetChargeMerchantFee returns the ChargeMerchantFee field value if set, zero value otherwise.
func (o *PaymentRefundEventData) GetChargeMerchantFee() bool {
	if o == nil || IsNil(o.ChargeMerchantFee) {
		var ret bool
		return ret
	}
	return *o.ChargeMerchantFee
}

// GetChargeMerchantFeeOk returns a tuple with the ChargeMerchantFee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentRefundEventData) GetChargeMerchantFeeOk() (*bool, bool) {
	if o == nil || IsNil(o.ChargeMerchantFee) {
		return nil, false
	}
	return o.ChargeMerchantFee, true
}

// HasChargeMerchantFee returns a boolean if a field has been set.
func (o *PaymentRefundEventData) HasChargeMerchantFee() bool {
	if o != nil && !IsNil(o.ChargeMerchantFee) {
		return true
	}

	return false
}

// SetChargeMerchantFee gets a reference to the given bool and assigns it to the ChargeMerchantFee field.
func (o *PaymentRefundEventData) SetChargeMerchantFee(v bool) {
	o.ChargeMerchantFee = &v
}

// GetMerchantFeeAmount returns the MerchantFeeAmount field value if set, zero value otherwise.
func (o *PaymentRefundEventData) GetMerchantFeeAmount() string {
	if o == nil || IsNil(o.MerchantFeeAmount) {
		var ret string
		return ret
	}
	return *o.MerchantFeeAmount
}

// GetMerchantFeeAmountOk returns a tuple with the MerchantFeeAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentRefundEventData) GetMerchantFeeAmountOk() (*string, bool) {
	if o == nil || IsNil(o.MerchantFeeAmount) {
		return nil, false
	}
	return o.MerchantFeeAmount, true
}

// HasMerchantFeeAmount returns a boolean if a field has been set.
func (o *PaymentRefundEventData) HasMerchantFeeAmount() bool {
	if o != nil && !IsNil(o.MerchantFeeAmount) {
		return true
	}

	return false
}

// SetMerchantFeeAmount gets a reference to the given string and assigns it to the MerchantFeeAmount field.
func (o *PaymentRefundEventData) SetMerchantFeeAmount(v string) {
	o.MerchantFeeAmount = &v
}

// GetMerchantFeeTokenId returns the MerchantFeeTokenId field value if set, zero value otherwise.
func (o *PaymentRefundEventData) GetMerchantFeeTokenId() string {
	if o == nil || IsNil(o.MerchantFeeTokenId) {
		var ret string
		return ret
	}
	return *o.MerchantFeeTokenId
}

// GetMerchantFeeTokenIdOk returns a tuple with the MerchantFeeTokenId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentRefundEventData) GetMerchantFeeTokenIdOk() (*string, bool) {
	if o == nil || IsNil(o.MerchantFeeTokenId) {
		return nil, false
	}
	return o.MerchantFeeTokenId, true
}

// HasMerchantFeeTokenId returns a boolean if a field has been set.
func (o *PaymentRefundEventData) HasMerchantFeeTokenId() bool {
	if o != nil && !IsNil(o.MerchantFeeTokenId) {
		return true
	}

	return false
}

// SetMerchantFeeTokenId gets a reference to the given string and assigns it to the MerchantFeeTokenId field.
func (o *PaymentRefundEventData) SetMerchantFeeTokenId(v string) {
	o.MerchantFeeTokenId = &v
}

// GetCommissionFee returns the CommissionFee field value if set, zero value otherwise.
func (o *PaymentRefundEventData) GetCommissionFee() CommissionFee {
	if o == nil || IsNil(o.CommissionFee) {
		var ret CommissionFee
		return ret
	}
	return *o.CommissionFee
}

// GetCommissionFeeOk returns a tuple with the CommissionFee field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PaymentRefundEventData) GetCommissionFeeOk() (*CommissionFee, bool) {
	if o == nil || IsNil(o.CommissionFee) {
		return nil, false
	}
	return o.CommissionFee, true
}

// HasCommissionFee returns a boolean if a field has been set.
func (o *PaymentRefundEventData) HasCommissionFee() bool {
	if o != nil && !IsNil(o.CommissionFee) {
		return true
	}

	return false
}

// SetCommissionFee gets a reference to the given CommissionFee and assigns it to the CommissionFee field.
func (o *PaymentRefundEventData) SetCommissionFee(v CommissionFee) {
	o.CommissionFee = &v
}

func (o PaymentRefundEventData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaymentRefundEventData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data_type"] = o.DataType
	if !IsNil(o.RequestId) {
		toSerialize["request_id"] = o.RequestId
	}
	toSerialize["refund_id"] = o.RefundId
	if !IsNil(o.OrderId) {
		toSerialize["order_id"] = o.OrderId
	}
	if !IsNil(o.MerchantId) {
		toSerialize["merchant_id"] = o.MerchantId
	}
	toSerialize["token_id"] = o.TokenId
	toSerialize["chain_id"] = o.ChainId
	toSerialize["amount"] = o.Amount
	toSerialize["to_address"] = o.ToAddress
	toSerialize["status"] = o.Status
	if !IsNil(o.RefundType) {
		toSerialize["refund_type"] = o.RefundType
	}
	if !IsNil(o.CreatedTimestamp) {
		toSerialize["created_timestamp"] = o.CreatedTimestamp
	}
	if !IsNil(o.UpdatedTimestamp) {
		toSerialize["updated_timestamp"] = o.UpdatedTimestamp
	}
	if !IsNil(o.Initiator) {
		toSerialize["initiator"] = o.Initiator
	}
	if !IsNil(o.Transactions) {
		toSerialize["transactions"] = o.Transactions
	}
	if !IsNil(o.ChargeMerchantFee) {
		toSerialize["charge_merchant_fee"] = o.ChargeMerchantFee
	}
	if !IsNil(o.MerchantFeeAmount) {
		toSerialize["merchant_fee_amount"] = o.MerchantFeeAmount
	}
	if !IsNil(o.MerchantFeeTokenId) {
		toSerialize["merchant_fee_token_id"] = o.MerchantFeeTokenId
	}
	if !IsNil(o.CommissionFee) {
		toSerialize["commission_fee"] = o.CommissionFee
	}
	return toSerialize, nil
}

func (o *PaymentRefundEventData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data_type",
		"refund_id",
		"token_id",
		"chain_id",
		"amount",
		"to_address",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPaymentRefundEventData := _PaymentRefundEventData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPaymentRefundEventData)

	if err != nil {
		return err
	}

	*o = PaymentRefundEventData(varPaymentRefundEventData)

	return err
}

type NullablePaymentRefundEventData struct {
	value *PaymentRefundEventData
	isSet bool
}

func (v NullablePaymentRefundEventData) Get() *PaymentRefundEventData {
	return v.value
}

func (v *NullablePaymentRefundEventData) Set(val *PaymentRefundEventData) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentRefundEventData) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentRefundEventData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentRefundEventData(val *PaymentRefundEventData) *NullablePaymentRefundEventData {
	return &NullablePaymentRefundEventData{value: val, isSet: true}
}

func (v NullablePaymentRefundEventData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentRefundEventData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


