/*
Cobo Wallet as a Service 2.0

Contact: help@cobo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cobo_waas2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TokenizationUpdateBlocklistAddressesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenizationUpdateBlocklistAddressesRequest{}

// TokenizationUpdateBlocklistAddressesRequest struct for TokenizationUpdateBlocklistAddressesRequest
type TokenizationUpdateBlocklistAddressesRequest struct {
	Action TokenizationUpdateAddressAction `json:"action"`
	Source TokenizationTokenOperationSource `json:"source"`
	// A list of addresses to manage. For 'add' operations, notes can be provided. For 'remove' operations, notes are ignored.
	Addresses []TokenizationUpdateBlocklistAddressesParamsAddressesInner `json:"addresses"`
	// The initiator of the tokenization activity. If you do not specify this property, the WaaS service will automatically designate the API key as the initiator.
	AppInitiator *string `json:"app_initiator,omitempty"`
	Fee TransactionRequestFee `json:"fee"`
	// The request ID that is used to track a transaction request. The request ID is provided by you and must be unique within your organization.
	RequestId *string `json:"request_id,omitempty"`
}

type _TokenizationUpdateBlocklistAddressesRequest TokenizationUpdateBlocklistAddressesRequest

// NewTokenizationUpdateBlocklistAddressesRequest instantiates a new TokenizationUpdateBlocklistAddressesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenizationUpdateBlocklistAddressesRequest(action TokenizationUpdateAddressAction, source TokenizationTokenOperationSource, addresses []TokenizationUpdateBlocklistAddressesParamsAddressesInner, fee TransactionRequestFee) *TokenizationUpdateBlocklistAddressesRequest {
	this := TokenizationUpdateBlocklistAddressesRequest{}
	this.Action = action
	this.Source = source
	this.Addresses = addresses
	this.Fee = fee
	return &this
}

// NewTokenizationUpdateBlocklistAddressesRequestWithDefaults instantiates a new TokenizationUpdateBlocklistAddressesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenizationUpdateBlocklistAddressesRequestWithDefaults() *TokenizationUpdateBlocklistAddressesRequest {
	this := TokenizationUpdateBlocklistAddressesRequest{}
	return &this
}

// GetAction returns the Action field value
func (o *TokenizationUpdateBlocklistAddressesRequest) GetAction() TokenizationUpdateAddressAction {
	if o == nil {
		var ret TokenizationUpdateAddressAction
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *TokenizationUpdateBlocklistAddressesRequest) GetActionOk() (*TokenizationUpdateAddressAction, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *TokenizationUpdateBlocklistAddressesRequest) SetAction(v TokenizationUpdateAddressAction) {
	o.Action = v
}

// GetSource returns the Source field value
func (o *TokenizationUpdateBlocklistAddressesRequest) GetSource() TokenizationTokenOperationSource {
	if o == nil {
		var ret TokenizationTokenOperationSource
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *TokenizationUpdateBlocklistAddressesRequest) GetSourceOk() (*TokenizationTokenOperationSource, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *TokenizationUpdateBlocklistAddressesRequest) SetSource(v TokenizationTokenOperationSource) {
	o.Source = v
}

// GetAddresses returns the Addresses field value
func (o *TokenizationUpdateBlocklistAddressesRequest) GetAddresses() []TokenizationUpdateBlocklistAddressesParamsAddressesInner {
	if o == nil {
		var ret []TokenizationUpdateBlocklistAddressesParamsAddressesInner
		return ret
	}

	return o.Addresses
}

// GetAddressesOk returns a tuple with the Addresses field value
// and a boolean to check if the value has been set.
func (o *TokenizationUpdateBlocklistAddressesRequest) GetAddressesOk() ([]TokenizationUpdateBlocklistAddressesParamsAddressesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Addresses, true
}

// SetAddresses sets field value
func (o *TokenizationUpdateBlocklistAddressesRequest) SetAddresses(v []TokenizationUpdateBlocklistAddressesParamsAddressesInner) {
	o.Addresses = v
}

// GetAppInitiator returns the AppInitiator field value if set, zero value otherwise.
func (o *TokenizationUpdateBlocklistAddressesRequest) GetAppInitiator() string {
	if o == nil || IsNil(o.AppInitiator) {
		var ret string
		return ret
	}
	return *o.AppInitiator
}

// GetAppInitiatorOk returns a tuple with the AppInitiator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenizationUpdateBlocklistAddressesRequest) GetAppInitiatorOk() (*string, bool) {
	if o == nil || IsNil(o.AppInitiator) {
		return nil, false
	}
	return o.AppInitiator, true
}

// HasAppInitiator returns a boolean if a field has been set.
func (o *TokenizationUpdateBlocklistAddressesRequest) HasAppInitiator() bool {
	if o != nil && !IsNil(o.AppInitiator) {
		return true
	}

	return false
}

// SetAppInitiator gets a reference to the given string and assigns it to the AppInitiator field.
func (o *TokenizationUpdateBlocklistAddressesRequest) SetAppInitiator(v string) {
	o.AppInitiator = &v
}

// GetFee returns the Fee field value
func (o *TokenizationUpdateBlocklistAddressesRequest) GetFee() TransactionRequestFee {
	if o == nil {
		var ret TransactionRequestFee
		return ret
	}

	return o.Fee
}

// GetFeeOk returns a tuple with the Fee field value
// and a boolean to check if the value has been set.
func (o *TokenizationUpdateBlocklistAddressesRequest) GetFeeOk() (*TransactionRequestFee, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Fee, true
}

// SetFee sets field value
func (o *TokenizationUpdateBlocklistAddressesRequest) SetFee(v TransactionRequestFee) {
	o.Fee = v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *TokenizationUpdateBlocklistAddressesRequest) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TokenizationUpdateBlocklistAddressesRequest) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *TokenizationUpdateBlocklistAddressesRequest) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *TokenizationUpdateBlocklistAddressesRequest) SetRequestId(v string) {
	o.RequestId = &v
}

func (o TokenizationUpdateBlocklistAddressesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenizationUpdateBlocklistAddressesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["action"] = o.Action
	toSerialize["source"] = o.Source
	toSerialize["addresses"] = o.Addresses
	if !IsNil(o.AppInitiator) {
		toSerialize["app_initiator"] = o.AppInitiator
	}
	toSerialize["fee"] = o.Fee
	if !IsNil(o.RequestId) {
		toSerialize["request_id"] = o.RequestId
	}
	return toSerialize, nil
}

func (o *TokenizationUpdateBlocklistAddressesRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"action",
		"source",
		"addresses",
		"fee",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTokenizationUpdateBlocklistAddressesRequest := _TokenizationUpdateBlocklistAddressesRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTokenizationUpdateBlocklistAddressesRequest)

	if err != nil {
		return err
	}

	*o = TokenizationUpdateBlocklistAddressesRequest(varTokenizationUpdateBlocklistAddressesRequest)

	return err
}

type NullableTokenizationUpdateBlocklistAddressesRequest struct {
	value *TokenizationUpdateBlocklistAddressesRequest
	isSet bool
}

func (v NullableTokenizationUpdateBlocklistAddressesRequest) Get() *TokenizationUpdateBlocklistAddressesRequest {
	return v.value
}

func (v *NullableTokenizationUpdateBlocklistAddressesRequest) Set(val *TokenizationUpdateBlocklistAddressesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenizationUpdateBlocklistAddressesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenizationUpdateBlocklistAddressesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenizationUpdateBlocklistAddressesRequest(val *TokenizationUpdateBlocklistAddressesRequest) *NullableTokenizationUpdateBlocklistAddressesRequest {
	return &NullableTokenizationUpdateBlocklistAddressesRequest{value: val, isSet: true}
}

func (v NullableTokenizationUpdateBlocklistAddressesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenizationUpdateBlocklistAddressesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


