/*
Cobo Wallet as a Service 2.0

Contact: help@cobo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cobo_waas2

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the KyaScreeningRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KyaScreeningRequest{}

// KyaScreeningRequest Individual address screening request.
type KyaScreeningRequest struct {
	// The request ID that is used to track a request. The request ID is provided by you and must be unique within your organization. This ID is used for idempotency to prevent duplicate submissions and for troubleshooting purposes.
	RequestId string `json:"request_id"`
	// The blockchain address to be screened. For chains requiring memo (XRP, EOS, XLM, IOST, BNB_BNB, ATOM, LUNA, TON), append the memo to the address using \"|\" separator (e.g., \"address|memo\"). 
	Address string `json:"address"`
	// The chain identifier (e.g., ETH, BTC, TRON).
	ChainId string `json:"chain_id"`
	// Optional note for this address screening.
	Note *string `json:"note,omitempty"`
}

type _KyaScreeningRequest KyaScreeningRequest

// NewKyaScreeningRequest instantiates a new KyaScreeningRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKyaScreeningRequest(requestId string, address string, chainId string) *KyaScreeningRequest {
	this := KyaScreeningRequest{}
	this.RequestId = requestId
	this.Address = address
	this.ChainId = chainId
	return &this
}

// NewKyaScreeningRequestWithDefaults instantiates a new KyaScreeningRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKyaScreeningRequestWithDefaults() *KyaScreeningRequest {
	this := KyaScreeningRequest{}
	return &this
}

// GetRequestId returns the RequestId field value
func (o *KyaScreeningRequest) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *KyaScreeningRequest) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *KyaScreeningRequest) SetRequestId(v string) {
	o.RequestId = v
}

// GetAddress returns the Address field value
func (o *KyaScreeningRequest) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *KyaScreeningRequest) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *KyaScreeningRequest) SetAddress(v string) {
	o.Address = v
}

// GetChainId returns the ChainId field value
func (o *KyaScreeningRequest) GetChainId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChainId
}

// GetChainIdOk returns a tuple with the ChainId field value
// and a boolean to check if the value has been set.
func (o *KyaScreeningRequest) GetChainIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChainId, true
}

// SetChainId sets field value
func (o *KyaScreeningRequest) SetChainId(v string) {
	o.ChainId = v
}

// GetNote returns the Note field value if set, zero value otherwise.
func (o *KyaScreeningRequest) GetNote() string {
	if o == nil || IsNil(o.Note) {
		var ret string
		return ret
	}
	return *o.Note
}

// GetNoteOk returns a tuple with the Note field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KyaScreeningRequest) GetNoteOk() (*string, bool) {
	if o == nil || IsNil(o.Note) {
		return nil, false
	}
	return o.Note, true
}

// HasNote returns a boolean if a field has been set.
func (o *KyaScreeningRequest) HasNote() bool {
	if o != nil && !IsNil(o.Note) {
		return true
	}

	return false
}

// SetNote gets a reference to the given string and assigns it to the Note field.
func (o *KyaScreeningRequest) SetNote(v string) {
	o.Note = &v
}

func (o KyaScreeningRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KyaScreeningRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["request_id"] = o.RequestId
	toSerialize["address"] = o.Address
	toSerialize["chain_id"] = o.ChainId
	if !IsNil(o.Note) {
		toSerialize["note"] = o.Note
	}
	return toSerialize, nil
}

func (o *KyaScreeningRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"request_id",
		"address",
		"chain_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKyaScreeningRequest := _KyaScreeningRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varKyaScreeningRequest)

	if err != nil {
		return err
	}

	*o = KyaScreeningRequest(varKyaScreeningRequest)

	return err
}

type NullableKyaScreeningRequest struct {
	value *KyaScreeningRequest
	isSet bool
}

func (v NullableKyaScreeningRequest) Get() *KyaScreeningRequest {
	return v.value
}

func (v *NullableKyaScreeningRequest) Set(val *KyaScreeningRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableKyaScreeningRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableKyaScreeningRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKyaScreeningRequest(val *KyaScreeningRequest) *NullableKyaScreeningRequest {
	return &NullableKyaScreeningRequest{value: val, isSet: true}
}

func (v NullableKyaScreeningRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKyaScreeningRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


