/*
Cobo Wallet as a Service 2.0

Contact: help@cobo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cobo_waas2

import (
	"encoding/json"
	"fmt"
)

// PaymentBalanceFlowDirection The direction of the balance change relative to the source account. Possible values include: - `in`: Funds flow into the source account. - `out`: Funds flow out of the source account. 
type PaymentBalanceFlowDirection string

// List of PaymentBalanceFlowDirection
const (
	PAYMENTBALANCEFLOWDIRECTION_IN PaymentBalanceFlowDirection = "in"
	PAYMENTBALANCEFLOWDIRECTION_OUT PaymentBalanceFlowDirection = "out"
)

// All allowed values of PaymentBalanceFlowDirection enum
var AllowedPaymentBalanceFlowDirectionEnumValues = []PaymentBalanceFlowDirection{
	"in",
	"out",
}

func (v *PaymentBalanceFlowDirection) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := PaymentBalanceFlowDirection(value)
	for _, existing := range AllowedPaymentBalanceFlowDirectionEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}
	*v = PaymentBalanceFlowDirection("unknown")
	return nil
}

// NewPaymentBalanceFlowDirectionFromValue returns a pointer to a valid PaymentBalanceFlowDirection
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewPaymentBalanceFlowDirectionFromValue(v string) (*PaymentBalanceFlowDirection, error) {
	ev := PaymentBalanceFlowDirection(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for PaymentBalanceFlowDirection: valid values are %v", v, AllowedPaymentBalanceFlowDirectionEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v PaymentBalanceFlowDirection) IsValid() bool {
	for _, existing := range AllowedPaymentBalanceFlowDirectionEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to PaymentBalanceFlowDirection value
func (v PaymentBalanceFlowDirection) Ptr() *PaymentBalanceFlowDirection {
	return &v
}

type NullablePaymentBalanceFlowDirection struct {
	value *PaymentBalanceFlowDirection
	isSet bool
}

func (v NullablePaymentBalanceFlowDirection) Get() *PaymentBalanceFlowDirection {
	return v.value
}

func (v *NullablePaymentBalanceFlowDirection) Set(val *PaymentBalanceFlowDirection) {
	v.value = val
	v.isSet = true
}

func (v NullablePaymentBalanceFlowDirection) IsSet() bool {
	return v.isSet
}

func (v *NullablePaymentBalanceFlowDirection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaymentBalanceFlowDirection(val *PaymentBalanceFlowDirection) *NullablePaymentBalanceFlowDirection {
	return &NullablePaymentBalanceFlowDirection{value: val, isSet: true}
}

func (v NullablePaymentBalanceFlowDirection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaymentBalanceFlowDirection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

