/*
Cobo Wallet as a Service 2.0

Contact: help@cobo.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package cobo_waas2

import (
	"encoding/json"
)

// checks if the ListApprovalRequests200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListApprovalRequests200Response{}

// ListApprovalRequests200Response struct for ListApprovalRequests200Response
type ListApprovalRequests200Response struct {
	Data []ApprovalRequest `json:"data,omitempty"`
	Pagination *Pagination `json:"pagination,omitempty"`
}

// NewListApprovalRequests200Response instantiates a new ListApprovalRequests200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListApprovalRequests200Response() *ListApprovalRequests200Response {
	this := ListApprovalRequests200Response{}
	return &this
}

// NewListApprovalRequests200ResponseWithDefaults instantiates a new ListApprovalRequests200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListApprovalRequests200ResponseWithDefaults() *ListApprovalRequests200Response {
	this := ListApprovalRequests200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ListApprovalRequests200Response) GetData() []ApprovalRequest {
	if o == nil || IsNil(o.Data) {
		var ret []ApprovalRequest
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListApprovalRequests200Response) GetDataOk() ([]ApprovalRequest, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ListApprovalRequests200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []ApprovalRequest and assigns it to the Data field.
func (o *ListApprovalRequests200Response) SetData(v []ApprovalRequest) {
	o.Data = v
}

// GetPagination returns the Pagination field value if set, zero value otherwise.
func (o *ListApprovalRequests200Response) GetPagination() Pagination {
	if o == nil || IsNil(o.Pagination) {
		var ret Pagination
		return ret
	}
	return *o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListApprovalRequests200Response) GetPaginationOk() (*Pagination, bool) {
	if o == nil || IsNil(o.Pagination) {
		return nil, false
	}
	return o.Pagination, true
}

// HasPagination returns a boolean if a field has been set.
func (o *ListApprovalRequests200Response) HasPagination() bool {
	if o != nil && !IsNil(o.Pagination) {
		return true
	}

	return false
}

// SetPagination gets a reference to the given Pagination and assigns it to the Pagination field.
func (o *ListApprovalRequests200Response) SetPagination(v Pagination) {
	o.Pagination = &v
}

func (o ListApprovalRequests200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListApprovalRequests200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Pagination) {
		toSerialize["pagination"] = o.Pagination
	}
	return toSerialize, nil
}

type NullableListApprovalRequests200Response struct {
	value *ListApprovalRequests200Response
	isSet bool
}

func (v NullableListApprovalRequests200Response) Get() *ListApprovalRequests200Response {
	return v.value
}

func (v *NullableListApprovalRequests200Response) Set(val *ListApprovalRequests200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListApprovalRequests200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListApprovalRequests200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListApprovalRequests200Response(val *ListApprovalRequests200Response) *NullableListApprovalRequests200Response {
	return &NullableListApprovalRequests200Response{value: val, isSet: true}
}

func (v NullableListApprovalRequests200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListApprovalRequests200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


